/**
 * ITR-3 — departmental JSON paths for assessment year 2026-27.
 *
 * Ported from docs/reference/ITR3-source.html. Every value here is the path the
 * Income Tax Department's schema expects; a changed path fails at upload with an
 * opaque error, so nothing in this file is tidied, renamed or reordered.
 *
 * Keys are fully qualified field keys, `${scheduleId}.${fieldKey}`, matching
 * ITR3_SCHEDULES. Paths are slash-delimited from the root of the return body.
 */

/** Order the top-level nodes are written in. The department reads the file positionally. */
export const SCH_ORDER: readonly string[] = [
  'CreationInfo',
  'Form_ITR3',
  'PartA_GEN1',
  'PartA_GEN2',
  'PARTA_BS',
  'PARTA_PL',
  'PARTA_OI',
  'ManufacturingAccount',
  'TradingAccount',
  'PARTA_QD',
  'ITR3ScheduleBP',
  'ScheduleDPM',
  'ScheduleDOA',
  'ScheduleDEP',
  'ScheduleDCG',
  'ScheduleESR',
  'ITR3ScheduleUD',
  'ScheduleICDS',
  'ScheduleTPSA',
  'ScheduleGST',
  'PartA_139_8A',
  'PartB-ATI',
  'ScheduleCYLA',
  'ScheduleBFLA',
  'ScheduleCFL',
  'PartB-TI',
  'PartB_TTI',
  'TaxReturnPreparer',
  'ScheduleIT',
  'ScheduleTDS1',
  'ScheduleTDS2',
  'ScheduleTDS3',
  'ScheduleTCS',
  'Verification',
  'ScheduleS',
  'ScheduleHP',
  'ScheduleCGFor23',
  'Schedule112A',
  'Schedule115AD',
  'ScheduleVDA',
  'ScheduleOS',
  'Schedule10AA',
  'Schedule80RA',
  'Schedule80_IA',
  'Schedule80_IB',
  'Schedule80_IC',
  'Schedule80GGA',
  'Schedule80G',
  'Schedule80D',
  'Schedule80GGC',
  'Schedule80DD',
  'Schedule80U',
  'Schedule80C',
  'Schedule80E',
  'Schedule80EE',
  'Schedule80EEA',
  'Schedule80EEB',
  'ScheduleAMT',
  'ScheduleVIA',
  'ScheduleAMTC',
  'ScheduleSI',
  'ScheduleSPI',
  'ScheduleIF',
  'ScheduleEI',
  'SchedulePTI',
  'ScheduleFSI',
  'ScheduleTR1',
  'ScheduleFA',
  'Schedule5A2014',
  'ScheduleAL',
  'ScheduleESOP',
];

/** Paths that must be emitted as JSON arrays even when they carry a single entry. */
export const SCH_ARRAYS: ReadonlySet<string> = new Set([
  'ITR3ScheduleBP/BusinessIncOthThanSpec/IncCredPL/OtherExmptIncDtl/OtherExmptIncDtls',
  'ITR3ScheduleBP/SpecifiedBusinessInc/DedUs35ADSubSec5Dtls',
  'ITR3ScheduleUD/ScheduleUD',
  'PARTA_PL/CreditsToPL/OthIncome/OtherIncDtls',
  'PARTA_PL/DebitsToPL/BadDebtDtls/BadDebtAmtDtls',
  'PARTA_PL/DebitsToPL/BadDebtDtls/OthersPANNotAvlblDtl',
  'PARTA_PL/DebitsToPL/OtherExpensesDtls',
  'PARTA_PL/GoodsDtlsUs44AE',
  'PARTA_PL/NatOfBus44AD',
  'PARTA_PL/NatOfBus44ADA',
  'PARTA_PL/NatOfBus44AE',
  'PARTA_PL/NonResidentPLDetails',
  'PARTA_QD/ManfactrConcern/FinishrByProd/QuantitDet',
  'PARTA_QD/ManfactrConcern/RawMaterial/QuantitDet',
  'PARTA_QD/TradingConcern/QuantitDet',
  'PartA_139_8A/RetrntoRedCarriedFL/UDYear/UnabsorbedDepreciationYearDtls',
  'PartA_139_8A/UpdatingInc/ReasonsForUpdatingIncDtls',
  'PartA_GEN1/FilingStatus/CompDirectorPrvYr/CompDirectorPrvYrDtls',
  'PartA_GEN1/FilingStatus/HeldUnlistedEqShrPrYr/HeldUnlistedEqShrPrYrDtls',
  'PartA_GEN1/FilingStatus/JurisdictionResPrevYr/JurisdictionResPrevYrDtls',
  'PartA_GEN1/FilingStatus/PartnerInFirm/PartnerInFirmDtls',
  'PartA_GEN1/FilingStatus/clauseiv7provisio139iDtls',
  'PartA_GEN2/AuditInfo/AuditDetails',
  'PartA_GEN2/AuditInfo/AuditReportDetails',
  'PartA_GEN2/NatOfBus/NatureOfBusiness',
  'PartB-ATI/ScheduleIT1/TaxPayment1/TaxPayments',
  'PartB-ATI/ScheduleIT2/TaxPayment2/TaxPayments',
  'PartB_TTI/Refund/BankAccountDtls/AddtnlBankDetails',
  'PartB_TTI/Refund/BankAccountDtls/ForeignBankDetails',
  'Schedule10AA/DeductSEZ/DedUs10Detail/Undertaking/DedFromUndertakingWithAy',
  'Schedule112A/Schedule112ADtls',
  'Schedule115AD/Schedule115ADDtls',
  'Schedule80C/Schedule80CDtls',
  'Schedule80D/Sec80DSelfFamSrCtznHealth/Sec80DParentsHIDtls/Sch80DInsDtls',
  'Schedule80D/Sec80DSelfFamSrCtznHealth/Sec80DParentsSrCtznHIDtls/Sch80DInsDtls',
  'Schedule80D/Sec80DSelfFamSrCtznHealth/Sec80DSelfFamHIDtls/Sch80DInsDtls',
  'Schedule80D/Sec80DSelfFamSrCtznHealth/Sec80DSelfFamSrCtznHIDtls/Sch80DInsDtls',
  'Schedule80E/Schedule80EDtls',
  'Schedule80EE/Schedule80EEDtls',
  'Schedule80EEA/Schedule80EEADtls',
  'Schedule80EEB/Schedule80EEBDtls',
  'Schedule80G/Don100Percent/DoneeWithPan',
  'Schedule80G/Don100PercentApprReqd/DoneeWithPan',
  'Schedule80G/Don50PercentApprReqd/DoneeWithPan',
  'Schedule80G/Don50PercentNoApprReqd/DoneeWithPan',
  'Schedule80GGA/DonationDtlsSciRsrchRuralDev',
  'Schedule80GGC/Schedule80GGCDetails',
  'Schedule80RA/DonationDtlsRsrchAssctn',
  'Schedule80_IA/DeductUs80_IA_4_iv/Sch80DeductAmtDtls',
  'Schedule80_IB/DeductFoodGrainUs80_IB_11A_Und/Sch80DeductAmtDtls',
  'Schedule80_IB/DeductFruitVegUs80_IB_11A_Und/Sch80DeductAmtDtls',
  'Schedule80_IB/DeductHousUs80_IB_10_Und/Sch80DeductAmtDtls',
  'Schedule80_IB/DeductMinOilUs80_IB_9_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/ArunachalPradesh_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Assam_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Manipur_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Meghalaya_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Mizoram_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Nagaland_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Sikkim_Und/Sch80DeductAmtDtls',
  'Schedule80_IC/DeductInNorthEast/Tripura_Und/Sch80DeductAmtDtls',
  'ScheduleAL/ImmovableDetails',
  'ScheduleAL/InterestHeldInaAsset',
  'ScheduleAMTC/ScheduleAMTCDtls',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs115F',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54B',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54D',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54EC',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54F',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54G',
  'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54GA',
  'ScheduleCGFor23/LongTermCapGain23/CapitalLossBuyBackShares/CapitalLossBuyBackSharesDtls',
  'ScheduleCGFor23/LongTermCapGain23/NRICgDTAA/NRIDTAADtls',
  'ScheduleCGFor23/LongTermCapGain23/NRIOnSec112and115/NRIOnSec112and115Dtls',
  'ScheduleCGFor23/LongTermCapGain23/Proviso112Applicable',
  'ScheduleCGFor23/LongTermCapGain23/SaleofAssetNADtls/SaleofAssetNA/ExemptionOrDednUs54/ExemptionOrDednUs54Dtls',
  'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/CostOfImprovements/CostOfImprovementsDtls',
  'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/ExemptionOrDednUs54/ExemptionOrDednUs54Dtls',
  'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/TrnsfImmblPrprty/TrnsfImmblPrprtyDtls',
  'ScheduleCGFor23/LongTermCapGain23/SlumpSaleInLtcgDtls/SlumpSaleInLtcg/ExemptionOrDednUs54/ExemptionOrDednUs54Dtls',
  'ScheduleCGFor23/LongTermCapGain23/UnutilizedCg/UnutilizedCgPrvYrDtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/CapitalLossBuyBackShares/CapitalLossBuyBackSharesDtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/EquityMFonSTT',
  'ScheduleCGFor23/ShortTermCapGainFor23/NRICgDTAA/NRIDTAADtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/SaleOnOtherAssets/ExemptionOrDednUs54/ExemptionOrDednUs54Dtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/CostOfImprovements/CostOfImprovementsDtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/ExemptionOrDednUs54/ExemptionOrDednUs54Dtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/TrnsfImmblPrprty/TrnsfImmblPrprtyDtls',
  'ScheduleCGFor23/ShortTermCapGainFor23/UnutilizedCg/UnutilizedCgPrvYrDtls',
  'ScheduleEI/ExcNetAgriInc/ExcNetAgriIncDtls',
  'ScheduleEI/IncNotChrgblAsPerDTAA/IncNotChrgblAsPerDTAADtls',
  'ScheduleEI/OthersInc/OthersIncDtls',
  'ScheduleESOP/ScheduleESOP2122_Type/ScheduleESOPEventDtls/ScheduleESOPEventDtlsType',
  'ScheduleESOP/ScheduleESOP2223_Type/ScheduleESOPEventDtls/ScheduleESOPEventDtlsType',
  'ScheduleESOP/ScheduleESOP2324_Type/ScheduleESOPEventDtls/ScheduleESOPEventDtlsType',
  'ScheduleESOP/ScheduleESOP2425_Type/ScheduleESOPEventDtls/ScheduleESOPEventDtlsType',
  'ScheduleESOP/ScheduleESOP2526_Type/ScheduleESOPEventDtls/ScheduleESOPEventDtlsType',
  'ScheduleFA/DetailsFinancialInterest',
  'ScheduleFA/DetailsForiegnBank',
  'ScheduleFA/DetailsImmovableProperty',
  'ScheduleFA/DetailsOfAccntsHvngSigningAuth',
  'ScheduleFA/DetailsOfOthSourcesIncOutsideIndia',
  'ScheduleFA/DetailsOfTrustOutIndiaTrustee',
  'ScheduleFA/DetailsOthAssets',
  'ScheduleFA/DtlsForeignCashValueInsurance',
  'ScheduleFA/DtlsForeignCustodialAcc',
  'ScheduleFA/DtlsForeignEquityDebtInterest',
  'ScheduleFSI/ScheduleFSIDtls',
  'ScheduleGST/TurnoverGrsRcptForGSTIN',
  'ScheduleHP/PropertyDetails',
  'ScheduleHP/PropertyDetails/CoOwners',
  'ScheduleHP/PropertyDetails/Rentdetails/Section24B/Section24BDtls',
  'ScheduleHP/PropertyDetails/TenantDetails',
  'ScheduleIF/PartnerFirmDetails',
  'ScheduleIT/TaxPayment',
  'ScheduleOS/IncOthThanOwnRaceHorse/IncChargblSplRateOS/NRIOsDTAA/NRIDTAADtlsSchOS',
  'ScheduleOS/IncOthThanOwnRaceHorse/IncomeNotified89ATypeOS',
  'ScheduleOS/IncOthThanOwnRaceHorse/OthersGrossDtls',
  'ScheduleOS/IncOthThanOwnRaceHorse/OthersInc/OthersIncDtls',
  'ScheduleOS/IncOthThanOwnRaceHorse/PTIOthersGrossDtls',
  'ScheduleOS/IncOthThanOwnRaceHorse/TaxAccumulatedBalRecPF/TaxAccmltdBalRecPFDtls',
  'SchedulePTI/SchedulePTIDtls',
  'ScheduleS/AllwncExemptUs10/AllwncExemptUs10Dtls',
  'ScheduleS/Salaries',
  'ScheduleS/Salaries/Salarys/IncomeNotified89AType',
  'ScheduleS/Salaries/Salarys/NatureOfPerquisites/OthersIncDtls',
  'ScheduleS/Salaries/Salarys/NatureOfProfitInLieuOfSalary/OthersIncDtls',
  'ScheduleS/Salaries/Salarys/NatureOfSalary/OthersIncDtls',
  'ScheduleSI/SplCodeRateTax',
  'ScheduleSPI/SpecifiedPerson',
  'ScheduleTCS/TCS',
  'ScheduleTDS1/TDSonSalary',
  'ScheduleTDS2/TDSOthThanSalaryDtls',
  'ScheduleTDS3/TDS3onOthThanSalDtls',
  'ScheduleTPSA/DtlsTaxesPaid',
  'ScheduleTR1/ScheduleTR',
  'ScheduleVDA/ScheduleVDADtls',
  'ScheduleVIA/UsrDeductUndChapVIA/PRANDtls',
  'ScheduleVIA/UsrDeductUndChapVIA/PensionContribution80CCC',
  'TradingAccount/OtherIncDtls',
  'TradingAccount/OtherOperatingRevenueDtls',
]);

/** Scalar field key to its path in the return body. */
export const SCH_FIELDS: Readonly<Record<string, string>> = {
  'GEN.FirstName': 'PartA_GEN1/PersonalInfo/AssesseeName/FirstName',
  'GEN.MiddleName': 'PartA_GEN1/PersonalInfo/AssesseeName/MiddleName',
  'GEN.SurNameOrOrgName': 'PartA_GEN1/PersonalInfo/AssesseeName/SurNameOrOrgName',
  'GEN.PAN': 'PartA_GEN1/PersonalInfo/PAN',
  'GEN.DOB': 'PartA_GEN1/PersonalInfo/DOB',
  'GEN.Status': 'PartA_GEN1/PersonalInfo/Status',
  'GEN.AadhaarCardNo': 'PartA_GEN1/PersonalInfo/AadhaarCardNo',
  'GEN.DOCB': 'PartA_GEN1/PersonalInfo/DateofBusCommencement',
  'GEN.FlatDoorNo': 'PartA_GEN1/PersonalInfo/Address/ResidenceNo',
  'GEN.PremiseName': 'PartA_GEN1/PersonalInfo/Address/ResidenceName',
  'GEN.RoadStreet': 'PartA_GEN1/PersonalInfo/Address/RoadOrStreet',
  'GEN.Locality': 'PartA_GEN1/PersonalInfo/Address/LocalityOrArea',
  'GEN.City': 'PartA_GEN1/PersonalInfo/Address/CityOrTownOrDistrict',
  'GEN.State': 'PartA_GEN1/PersonalInfo/Address/StateCode',
  'GEN.Country': 'PartA_GEN1/PersonalInfo/Address/CountryCode',
  'GEN.PinCode': 'PartA_GEN1/PersonalInfo/Address/PinCode',
  'GEN.SecAddSame': 'PartA_GEN1/PersonalInfo/SecondaryAdd',
  'GEN.EmailAddress': 'PartA_GEN1/PersonalInfo/Address/EmailAddress',
  'GEN.MobileNo': 'PartA_GEN1/PersonalInfo/Address/MobileNo',
  'GEN.MobileNo2': 'PartA_GEN1/PersonalInfo/Address/MobileNoSec',
  'GEN.ResidentialStatus': 'PartA_GEN1/FilingStatus/ResidentialStatus',
  'GEN.JurisdictionResidence': 'PartA_GEN1/FilingStatus/JurisdictionResPrevYr/JurisdictionResPrevYrDtls/JurisdictionResidence',
  'GEN.StayInIndiaDays': 'PartA_GEN1/FilingStatus/TotalPrStayIndiaPrevYr',
  'GEN.ReturnFileSec': 'PartA_GEN1/FilingStatus/ReturnFileSec',
  'GEN.NoticeDIN': 'PartA_GEN1/FilingStatus/NoticeNo',
  'GEN.NoticeDate': 'PartA_GEN1/FilingStatus/NoticeDate',
  'GEN.OrigRetAckNo': 'PartA_GEN1/FilingStatus/ReceiptNo',
  'GEN.OrigRetDate': 'PartA_GEN1/FilingStatus/OrigRetFiledDate',
  'GEN.DueDate': 'PartA_GEN1/FilingStatus/ItrFilingDueDate',
  'GEN.OptOutNewTaxRegime': 'PartA_GEN1/FilingStatus/OptOldRegimeCurrAY',
  'GEN.BusIncomeFlag': 'PartA_GEN1/FilingStatus/IncFrmBusOrProf',
  'GEN.SeventhProviso139': 'PartA_GEN1/FilingStatus/SeventhProvisio139',
  'GEN.LiableAudit44AB': 'PartA_GEN2/AuditInfo/LiableSec44ABflg',
  'GEN.Audit44ABCondition': 'PartA_GEN2/AuditInfo/Cndnfor44AB',
  'GEN.AuditedFlag': 'PartA_GEN2/AuditInfo/AuditAccountantFlg',
  'GEN.AuditFirmName': 'PartA_GEN2/AuditInfo/AudFrmName',
  'GEN.AuditFirmPAN': 'PartA_GEN2/AuditInfo/AudFrmPAN',
  'GEN.AuditReportDate': 'PartA_GEN2/AuditInfo/AuditReportFurnishDate',
  'GEN.AuditFurnishDate': 'PartA_GEN2/AuditInfo/AuditReportFurnishDate',
  'GEN.Liable92E': 'PartA_GEN2/AuditInfo/LiableSec92Eflg',
  'GEN.PresumptiveOnly': 'PartA_GEN2/AuditInfo/IncDclrdUs',
  'GEN.TurnoverRange': 'PartA_GEN2/AuditInfo/TotalSalesExcOneCr',
  'GEN.CashReceiptPct': 'PartA_GEN2/AuditInfo/AgrOFAllAmtsRcvd',
  'GEN.CashPaymentPct': 'PartA_GEN2/AuditInfo/AgrOFAllPayMade',
  'GEN.FPIFlag': 'PartA_GEN1/FilingStatus/FiiFpiFlag',
  'GEN.PortugueseCC': 'PartA_GEN1/FilingStatus/PortugeseCC5A',
  'GEN.SpousePAN': 'Schedule5A2014/PANOfSpouse',
  'GEN.RepAssesseeFlag': 'PartA_GEN1/FilingStatus/AsseseeRepFlg',
  'GEN.RepName': 'PartA_GEN1/FilingStatus/AssesseeRep/RepName',
  'BS.PropCapital': 'PARTA_BS/FundSrc/PropFund/PropCap',
  'BS.RevSurplus': 'PARTA_BS/FundSrc/PropFund/ResrNSurp/RevResr',
  'BS.CapReserve': 'PARTA_BS/FundSrc/PropFund/ResrNSurp/CapResr',
  'BS.StatReserve': 'PARTA_BS/FundSrc/PropFund/ResrNSurp/StatResr',
  'BS.OthReserve': 'PARTA_BS/FundSrc/PropFund/ResrNSurp/OthResr',
  'BS.TotReserve': 'PARTA_BS/FundSrc/PropFund/ResrNSurp/TotResrNSurp',
  'BS.TotPropFund': 'PARTA_BS/FundSrc/PropFund/TotPropFund',
  'BS.SecuredLoansFin': 'PARTA_BS/FundSrc/LoanFunds/SecrLoan/RupeeLoan/FrmBank',
  'BS.SecuredLoansOth': 'PARTA_BS/FundSrc/LoanFunds/SecrLoan/RupeeLoan/FrmOthrs',
  'BS.UnsecuredLoans': 'PARTA_BS/FundSrc/LoanFunds/UnsecrLoan/TotUnSecrLoan',
  'BS.TotLoanFunds': 'PARTA_BS/FundSrc/LoanFunds/TotLoanFund',
  'BS.DefTaxLiab': 'PARTA_BS/FundSrc/DeferredTax',
  'BS.AdvFrom40A2b': 'PARTA_BS/FundSrc/Advances/FromPrsn',
  'BS.AdvFromOthers': 'PARTA_BS/FundSrc/Advances/FromOthers',
  'BS.TotAdvances': 'PARTA_BS/FundSrc/Advances/TotalAdvances',
  'BS.SourcesTotal': 'PARTA_BS/FundSrc/TotFundSrc',
  'BS.FixedAssetsNet': 'PARTA_BS/FundApply/FixedAsset/TotFixedAsset',
  'BS.LTInvest': 'PARTA_BS/FundApply/Investments/LongTermInv/TotLongTermInv',
  'BS.STInvest': 'PARTA_BS/FundApply/Investments/TradeInv/TotTradeInv',
  'BS.TotInvest': 'PARTA_BS/FundApply/Investments/TotInvestments',
  'BS.Inventories': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrAsset/Inventories/TotInventries',
  'BS.SundryDebtors': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrAsset/SndryDebtors',
  'BS.CashBank': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrAsset/CashOrBankBal/TotCashOrBankBal',
  'BS.OthCurrAssets': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrAsset/OthCurrAsset',
  'BS.LoansAdvGiven': 'PARTA_BS/FundApply/CurrAssetLoanAdv/LoanAdv/TotLoanAdv',
  'BS.TotCurrAssets': 'PARTA_BS/FundApply/CurrAssetLoanAdv/TotCurrAssetLoanAdv',
  'BS.CurrLiab': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrLiabilitiesProv/CurrLiabilities/TotCurrLiabilities',
  'BS.Provisions': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrLiabilitiesProv/Provisions/TotProvisions',
  'BS.TotCurrLiab': 'PARTA_BS/FundApply/CurrAssetLoanAdv/CurrLiabilitiesProv/TotCurrLiabilitiesProvision',
  'BS.NetCurrAssets': 'PARTA_BS/FundApply/CurrAssetLoanAdv/NetCurrAsset',
  'BS.MiscExp': 'PARTA_BS/FundApply/MiscAdjust/TotMiscAdjust',
  'BS.ApplicationTotal': 'PARTA_BS/FundApply/TotFundApply',
  'BS.NoAccCashBal': 'PARTA_BS/NoBooksOfAccBS/CashBalAmt',
  'BS.NoAccDebtors': 'PARTA_BS/NoBooksOfAccBS/TotSundryDbtAmt',
  'BS.NoAccCreditors': 'PARTA_BS/NoBooksOfAccBS/TotSundryCrdAmt',
  'BS.NoAccStock': 'PARTA_BS/NoBooksOfAccBS/TotStkInTradAmt',
  'MFG.OpRawMat': 'ManufacturingAccount/OpeningInventory/OpngStckRawMat',
  'MFG.OpWIP': 'ManufacturingAccount/OpeningInventory/OpngStckWrkinPrgrs',
  'MFG.OpTotal': 'ManufacturingAccount/OpeningInventory/OpngInvntryTotal',
  'MFG.Purchases': 'ManufacturingAccount/OpeningInventory/Purchases',
  'MFG.DirectWages': 'ManufacturingAccount/OpeningInventory/DirectWages',
  'MFG.DirectExpTotal': 'ManufacturingAccount/OpeningInventory/DirectExpenses',
  'MFG.FactoryOverheads': 'ManufacturingAccount/OpeningInventory/TotalFactoryOverheads',
  'MFG.FactoryDep': 'ManufacturingAccount/OpeningInventory/DeprctnOfFactoryMachinery',
  'MFG.TotalDebits': 'ManufacturingAccount/OpeningInventory/TotalDebtsManfctrngAcc',
  'MFG.ClosingStock': 'ManufacturingAccount/ClosingStock/ClsngStckTotal',
  'MFG.CostGoodsProduced': 'ManufacturingAccount/CostOfGoodsPrdcd',
  'TRD.SaleGoods': 'TradingAccount/SaleOfGoods',
  'TRD.SaleServices': 'TradingAccount/SaleOfServices',
  'TRD.OtherOpRevenue': 'TradingAccount/OperatingRevenueTotal',
  'TRD.GrossReceipts': 'TradingAccount/SalesGrossReceiptsTotal',
  'TRD.GrossReceiptsGST': 'TradingAccount/GrossRcptFromProfession',
  'TRD.DutiesTotal': 'TradingAccount/ExciseCustomsVAT/TotExciseCustomsVAT',
  'TRD.TotRevenueOps': 'TradingAccount/TotRevenueFrmOperations',
  'TRD.ClosingStockTrd': 'TradingAccount/ClsngStckOfFinishedStcks',
  'TRD.TotalOfCredits': 'TradingAccount/TardingAccTotCred',
  'TRD.OpStockFG': 'TradingAccount/OpngStckOfFinishedStcks',
  'TRD.PurchasesTrd': 'TradingAccount/Purchases',
  'TRD.DirectExpTrd': 'TradingAccount/DirectExpensesTotal',
  'TRD.DutiesTaxesPaid': 'TradingAccount/DutyTaxPay/ExciseCustomsVAT/TotExciseCustomsVAT',
  'TRD.CostGoodsFromMfg': 'TradingAccount/GoodsCostPrdcdFrmMA',
  'TRD.GrossProfit': 'TradingAccount/GrossProfitFrmBusProf',
  'TRD.IntradayTurnover': 'TradingAccount/TurnoverIntradayTrd',
  'TRD.IntradayIncome': 'TradingAccount/IncomeIntradayTrd',
  'TRD.FOTurnover': 'TradingAccount/TurnoverFutureTrd',
  'TRD.FOIncome': 'TradingAccount/IncomeFutureTrd',
  'PL.GrossProfitTrf': 'PARTA_PL/CreditsToPL/GrossProfitTrnsfFrmTrdAcc',
  'PL.OtherIncTotal': 'PARTA_PL/CreditsToPL/OthIncome/TotOthIncome',
  'PL.DividendInc14iii': 'PARTA_PL/CreditsToPL/OthIncome/Dividends',
  'PL.TotalCredits': 'PARTA_PL/CreditsToPL/TotCreditsToPL',
  'PL.EmpComp': 'PARTA_PL/DebitsToPL/EmployeeComp/TotEmployeeComp',
  'PL.Insurance': 'PARTA_PL/DebitsToPL/Insurances/TotInsurances',
  'PL.CommissionTot': 'PARTA_PL/DebitsToPL/CommissionExpdrDtls/Total',
  'PL.RoyaltyTot': 'PARTA_PL/DebitsToPL/RoyalityDtls/Total',
  'PL.ProfFees': 'PARTA_PL/DebitsToPL/ProfessionalConstDtls/Total',
  'PL.OtherExp': 'PARTA_PL/DebitsToPL/OtherExpenses',
  'PL.BadDebt': 'PARTA_PL/DebitsToPL/BadDebtDtls/BadDebt',
  'PL.ProvBadDebt': 'PARTA_PL/DebitsToPL/ProvForBadDoubtDebt',
  'PL.OtherProv': 'PARTA_PL/DebitsToPL/OthProvisionsExpdr',
  'PL.PBIDT': 'PARTA_PL/DebitsToPL/PBIDTA',
  'PL.InterestTot': 'PARTA_PL/DebitsToPL/InterestExpdrtDtls/InterestExpdr',
  'PL.Depreciation52': 'PARTA_PL/DebitsToPL/DepreciationAmort',
  'PL.NPBT': 'PARTA_PL/DebitsToPL/PBT',
  'PL.ProvCurrTax': 'PARTA_PL/TaxProvAppr/ProvForCurrTax',
  'PL.ProvDefTax': 'PARTA_PL/TaxProvAppr/ProvDefTax',
  'PL.PAT': 'PARTA_PL/TaxProvAppr/ProfitAfterTax',
  'PL.BalBroughtFwd': 'PARTA_PL/TaxProvAppr/BalBFPrevYr',
  'PL.AmtAvailAppr': 'PARTA_PL/TaxProvAppr/AmtAvlAppr',
  'PL.Appropriations': 'PARTA_PL/TaxProvAppr/TrfToReserves',
  'PL.BalCarriedBS': 'PARTA_PL/TaxProvAppr/ProprietorAccBalTrf',
  'PL.GT44ADBank': 'PARTA_PL/PersumptiveInc44AD/GrsTrnOverBank',
  'PL.GT44ADCash': 'PARTA_PL/PersumptiveInc44AD/GrsTotalTrnOverInCash',
  'PL.GT44ADOther': 'PARTA_PL/PersumptiveInc44AD/GrsTrnOverAnyOthMode',
  'PL.PI44ADBank': 'PARTA_PL/PersumptiveInc44AD/PersumptiveInc44AD6Per',
  'PL.PI44ADCash': 'PARTA_PL/PersumptiveInc44AD/PersumptiveInc44AD8Per',
  'PL.GR44ADA': 'PARTA_PL/PersumptiveInc44ADA/GrsReceipt',
  'PL.PI44ADA': 'PARTA_PL/PersumptiveInc44ADA/TotPersumptiveInc44ADA',
  'PL.PI44AE': 'PARTA_PL/TotalPrsumptvIncUs44EGoods',
  'PL.NA_BusGR': 'PARTA_PL/NoBooksOfAccPL/GrossReceipt',
  'PL.NA_BusGP': 'PARTA_PL/NoBooksOfAccPL/GrossProfit',
  'PL.NA_BusExp': 'PARTA_PL/NoBooksOfAccPL/Expenses',
  'PL.NA_BusNP': 'PARTA_PL/NoBooksOfAccPL/NetProfit',
  'PL.NA_ProfGR': 'PARTA_PL/NoBooksOfAccPL/GrossReceiptPrf',
  'PL.NA_ProfGP': 'PARTA_PL/NoBooksOfAccPL/GrossProfitPrf',
  'PL.NA_ProfExp': 'PARTA_PL/NoBooksOfAccPL/ExpensesPrf',
  'PL.NA_ProfNP': 'PARTA_PL/NoBooksOfAccPL/NetProfitPrf',
  'PL.NA_Total': 'PARTA_PL/NoBooksOfAccPL/TotBusinessProfession',
  'PL.SpecTurnover': 'PARTA_PL/TurnverFrmSpecActivity',
  'PL.SpecGP': 'PARTA_PL/GrossProfit',
  'PL.SpecExp': 'PARTA_PL/Expenditure',
  'PL.SpecNet': 'PARTA_PL/NetIncomeFrmSpecActivity',
  'PL.OthPresSec': 'PARTA_PL/NonResidentPLDetails/Section',
  'PL.OthPresGR': 'PARTA_PL/NonResidentPLDetails/GrossReceipt',
  'PL.OthPresNP': 'PARTA_PL/NonResidentPLDetails/NetProfit',
  'OI.MethodAcc': 'PARTA_OI/MethodOfAcct',
  'OI.MethodChange': 'PARTA_OI/ChangeInAcctMethFlg',
  'OI.ICDSIncrease': 'PARTA_OI/ProfDeviatDueAcctMeth',
  'OI.ICDSDecrease': 'PARTA_OI/DecProOrIncLossUs145_2',
  'OI.MethodValStock': 'PARTA_OI/MethodOfValClgStk/ValRawMaterial',
  'OI.NotCredited5f': 'PARTA_OI/NoCredToPLAmt/TotNoCredToPLAmt',
  'OI.Disallow36': 'PARTA_OI/AmtDisallUs36/TotAmtDisallUs36',
  'OI.Disallow37': 'PARTA_OI/AmtDisallUs37/TotAmtDisallUs37',
  'OI.Disallow40': 'PARTA_OI/AmtDisallUs40/TotAmtDisallUs40',
  'OI.Allow40PY': 'PARTA_OI/AmtDisallUs40/AmtDisallUs40PyNowAll',
  'OI.Disallow40A': 'PARTA_OI/AmtDisallUs40A/TotAmtDisallUs40A',
  'OI.Allow43B': 'PARTA_OI/AmtDisallUs43BPyNowAll/AmtUs43B/TotAmtUs43b',
  'OI.Disallow43B': 'PARTA_OI/AmtDisall43B/AmtUs43B/TotAmtUs43b',
  'OI.MSMEBeyond': 'PARTA_OI/AmtDisall43B/AmtUs43B/MSEPayable',
  'OI.OutstandingTax12i': 'PARTA_OI/AmtExciseCustomsVATOutstanding/ExciseCustomsVAT/TotExciseCustomsVAT',
  'OI.Deemed33AB': 'PARTA_OI/DeemedProfUs33ABs',
  'OI.Profit41': 'PARTA_OI/ProfTaxAmtUs41',
  'OI.Disallow14A': 'PARTA_OI/AmountOfExpDisAllwUs14A',
  'OI.IntMSME23': 'PARTA_OI/InterestDisAllowUs23SMEAct',
  'OI.Sec92CE2A': 'PARTA_OI/ScheduleTPSAFlg',
  'S.EmployerName': 'ScheduleS/Salaries/NameOfEmployer',
  'S.EmployerTAN': 'ScheduleS/Salaries/TANofEmployer',
  'S.EmployerCategory': 'ScheduleS/Salaries/NatureOfEmployment',
  'S.Sal17_1': 'ScheduleS/Salaries/Salarys/Salary',
  'S.Perq17_2': 'ScheduleS/Salaries/Salarys/ValueOfPerquisites',
  'S.Profit17_3': 'ScheduleS/Salaries/Salarys/ProfitsinLieuOfSalary',
  'S.Income89A_1d': 'ScheduleS/Salaries/Salarys/IncomeNotified89A',
  'S.Income89A_1e': 'ScheduleS/Salaries/Salarys/IncomeNotifiedOther89A',
  'S.GrossSalary': 'ScheduleS/TotalGrossSalary',
  'S.ExemptAllow': 'ScheduleS/AllwncExtentExemptUs10',
  'S.HRAExempt': 'ScheduleS/Section10_13A/EligbleExmpAllwncUs13A',
  'S.HRABasicDA': 'ScheduleS/Section10_13A/DtlsSalUsSec171',
  'S.HRAReceived': 'ScheduleS/Section10_13A/ActlHRARecv',
  'S.HRARentPaid': 'ScheduleS/Section10_13A/ActlRentPaid',
  'S.HRAMetro': 'ScheduleS/Section10_13A/Placeofwork',
  'S.NetSalary': 'ScheduleS/NetSalary',
  'S.StdDeduction': 'ScheduleS/DeductionUnderSection16ia',
  'S.EntAllow': 'ScheduleS/EntertainmntalwncUs16ii',
  'S.ProfTax': 'ScheduleS/ProfessionalTaxUs16iii',
  'S.IncomeSalaries': 'ScheduleS/TotIncUnderHeadSalaries',
  'S.Relief89A': 'ScheduleS/Increliefus89A',
  'HP.TotalHP': 'ScheduleHP/TotalIncomeChargeableUnHP',
  'BP.A1_ProfitPL': 'ITR3ScheduleBP/BusinessIncOthThanSpec/ProfBfrTaxPL',
  'BP.A2a_SpecProfit': 'ITR3ScheduleBP/BusinessIncOthThanSpec/NetPLFromSpecBus',
  'BP.A2b_SpecifiedProfit': 'ITR3ScheduleBP/BusinessIncOthThanSpec/NetPLFromSpecifiedBus',
  'BP.A3a_SalaryInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/Salary',
  'BP.A3b_HPInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/HouseProperty',
  'BP.A3c_CGInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/CapitalGains',
  'BP.A3d_OSInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/OtherSources',
  'BP.A3e_115BBF': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/Us115BBF',
  'BP.A3f_115BBG': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/Us115BBG',
  'BP.A3g_115BBH': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncRecCredPLOthHeadDtls/115BBH',
  'BP.A4a_ExemptInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncCredPL/TotExempIncPL',
  'BP.A4b_Rule7': 'ITR3ScheduleBP/BusinessIncOthThanSpec/TotalProfitFrmActCvrd',
  'BP.A5a_FirmShare': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncCredPL/FirmShareInc',
  'BP.A5c_DividendRed': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncCredPL/OtherExmptIncDtl/OperatingDividendAmt',
  'BP.A6_Balance': 'ITR3ScheduleBP/BusinessIncOthThanSpec/BalancePLOthThanSpecBus',
  'BP.A9_Additions': 'ITR3ScheduleBP/BusinessIncOthThanSpec/TotExpDebPL',
  'BP.A10': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AdjustedPLOthThanSpecBus',
  'BP.A11_Depreciation': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DepreciationDebPLCosAct',
  'BP.A12i_DepIT': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DepreciationAllowITAct32/DepreciationAllowUs32_1_ii',
  'BP.A12ii_Dep32_1i': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DepreciationAllowITAct32/DepreciationAllowUs32_1_i',
  'BP.A13': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AdjustPLAfterDeprOthSpecInc',
  'BP.A14_Dis36': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AmtDebPLDisallowUs36',
  'BP.A15_Dis37': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AmtDebPLDisallowUs37',
  'BP.A16_Dis40': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AmtDebPLDisallowUs40',
  'BP.A17_Dis40A': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AmtDebPLDisallowUs40A',
  'BP.A18_Dis43B': 'ITR3ScheduleBP/BusinessIncOthThanSpec/AmtDebPLDisallowUs43B',
  'BP.A22_Interest23': 'ITR3ScheduleBP/BusinessIncOthThanSpec/InterestDisAllowUs23SMEAct',
  'BP.A24e_ESRNeg': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DeemIncUs35ABA',
  'BP.A25_ICDSInc': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncProfDecLossAccICDSAdj',
  'BP.A26': 'ITR3ScheduleBP/BusinessIncOthThanSpec/TotAfterAddToPLDeprOthSpecInc',
  'BP.A28_ESRDeduction': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DebPLUs35ExcessAmt',
  'BP.A32_ICDSDec': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DecProfIncLossAccICDSAdj',
  'BP.A33': 'ITR3ScheduleBP/BusinessIncOthThanSpec/TotDeductionAmts',
  'BP.A34_Income': 'ITR3ScheduleBP/BusinessIncOthThanSpec/PLAftAdjDedBusOthThanSpec',
  'BP.A35i_44AD': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DeemedProfitBusUs/Section44AD',
  'BP.A35ii_44ADA': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DeemedProfitBusUs/Section44ADA',
  'BP.A35iii_44AE': 'ITR3ScheduleBP/BusinessIncOthThanSpec/DeemedProfitBusUs/Section44AE',
  'BP.A36_NetPGBP': 'ITR3ScheduleBP/BusinessIncOthThanSpec/NetPLAftAdjBusOthThanSpec',
  'BP.A37': 'ITR3ScheduleBP/BusinessIncOthThanSpec/IncomeOtherThanRule',
  'BP.A38_AgriDeemed': 'ITR3ScheduleBP/BusinessIncOthThanSpec/BalIncDeemedFrmAgri',
  'BP.B39_SpecPL': 'ITR3ScheduleBP/SpecBusinessInc/NetPLFrmSpecBus',
  'BP.B42_SpecIncome': 'ITR3ScheduleBP/SpecBusinessInc/AdjustedPLFrmSpecuBus',
  'BP.C43_SpecifiedPL': 'ITR3ScheduleBP/SpecifiedBusinessInc/NetPLFrmSpecifiedBus',
  'BP.SpecifiedNature': 'ITR3ScheduleBP/SpecifiedBusinessInc/DedUs35ADSubSec5Dtls/DedUs35ADSubSec5',
  'BP.C48_SpecifiedIncome': 'ITR3ScheduleBP/SpecifiedBusinessInc/PLFrmSpecifiedBus',
  'BP.D_TotalPGBP': 'ITR3ScheduleBP/IncChrgUnHdProftGain',
  'DEP.PM15_WDV': 'ScheduleDPM/PlantMachinery/Rate15/DepreciationDetail/WDVFirstDay',
  'DEP.PM15_Add': 'ScheduleDPM/PlantMachinery/Rate15/DepreciationDetail/AdditionsGrThan180Days',
  'DEP.PM15_Sale': 'ScheduleDPM/PlantMachinery/Rate15/DepreciationDetail/RealizationTotalPeriod',
  'DEP.PM15_Dep': 'ScheduleDPM/PlantMachinery/Rate15/DepreciationDetail/TotalDepreciation',
  'DEP.PM30_Dep': 'ScheduleDPM/PlantMachinery/Rate30/DepreciationDetail/TotalDepreciation',
  'DEP.PM40_Dep': 'ScheduleDPM/PlantMachinery/Rate40/DepreciationDetail/TotalDepreciation',
  'DEP.PM45_Dep': 'ScheduleDPM/PlantMachinery/Rate45/DepreciationDetail/TotalDepreciation',
  'DEP.AddlDep': 'ScheduleDPM/PlantMachinery/Rate15/DepreciationDetail/AddlnDeprOnGT180DayAdditions',
  'DEP.Bld5_Dep': 'ScheduleDOA/Building/Rate5/DepreciationDetail/TotalDepreciation',
  'DEP.Bld10_Dep': 'ScheduleDOA/Building/Rate10/DepreciationDetail/TotalDepreciation',
  'DEP.Bld40_Dep': 'ScheduleDOA/Building/Rate40/DepreciationDetail/TotalDepreciation',
  'DEP.Furn10_Dep': 'ScheduleDOA/FurnitureFittings/Rate10/DepreciationDetail/TotalDepreciation',
  'DEP.Intang25_Dep': 'ScheduleDOA/IntangibleAssets/Rate25/DepreciationDetail/TotalDepreciation',
  'DEP.Ships20_Dep': 'ScheduleDOA/Ships/Rate20/DepreciationDetail/TotalDepreciation',
  'DEP.DEP_Total': 'ScheduleDEP/SummaryFromDeprSch/TotalDepreciation',
  'DEP.DCG_Total': 'ScheduleDCG/SummaryFromDeprSchCG/TotalDepreciation',
  'ESR.ESR_35_1_i': 'ScheduleESR/DeductionUs35/Section35_1_i/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_1_ii': 'ScheduleESR/DeductionUs35/Section35_1_ii/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_1_iia': 'ScheduleESR/DeductionUs35/Section35_1_iia/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_1_iii': 'ScheduleESR/DeductionUs35/Section35_1_iii/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_1_iv': 'ScheduleESR/DeductionUs35/Section35_1_iv/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_2AA': 'ScheduleESR/DeductionUs35/Section35_2AA/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35_2AB': 'ScheduleESR/DeductionUs35/Section35_2AB/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35CCC': 'ScheduleESR/DeductionUs35/Section35_CCC/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_35CCD': 'ScheduleESR/DeductionUs35/Section35_CCD/DeductUs35/AmtUs35Allowable',
  'ESR.ESR_Excess': 'ScheduleESR/DeductionUs35/TotUs35/DeductUs35/ExcessAmtOverDebPL',
  'CG.STCG_A1_LandBld': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/FullConsideration',
  'CG.STCG_A1_Cost': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/AquisitCost',
  'CG.STCG_A1_Improve': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/ImproveCost',
  'CG.STCG_A1_Exp': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/ExpOnTrans',
  'CG.STCG_A1e': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls/CapgainonAssets',
  'CG.STCG_A2': 'ScheduleCGFor23/ShortTermCapGainFor23/SlumpSaleInStcg/CapgainonAssets',
  'CG.STCG_A3_111A': 'ScheduleCGFor23/ShortTermCapGainFor23/EquityMFonSTT/EquityMFonSTTDtls/CapgainonAssets',
  'CG.STCG_A5_NR': 'ScheduleCGFor23/ShortTermCapGainFor23/NRISecur115AD/CapgainonAssets',
  'CG.STCG_A6_Other': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleOnOtherAssets/CapgainonAssets',
  'CG.STCG_A7_PTI': 'ScheduleCGFor23/ShortTermCapGainFor23/PassThrIncNatureSTCG',
  'CG.STCG_A8_DTAA': 'ScheduleCGFor23/ShortTermCapGainFor23/TotalAmtTaxUsDTAAStcg',
  'CG.STCG_A9_Total': 'ScheduleCGFor23/ShortTermCapGainFor23/TotalSTCG',
  'CG.LTCG_B1_LandBld': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/FullConsideration',
  'CG.LTCG_B1_IndexCost': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/AquisitCost',
  'CG.LTCG_B1_PurDate': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/DateofPurchase',
  'CG.LTCG_B1_SaleDate': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/DateofSale',
  'CG.LTCG_B1e': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls/CapgainonAssets',
  'CG.LTCG_B2_SlumpSale': 'ScheduleCGFor23/LongTermCapGain23/SlumpSaleInLtcgDtls/SlumpSaleInLtcg/CapgainonAssets',
  'CG.LTCG_B3_Bonds': 'ScheduleCGFor23/LongTermCapGain23/Proviso112Applicable/Proviso112Applicabledtls/CapgainonAssets',
  'CG.LTCG_B4_112A': 'ScheduleCGFor23/LongTermCapGain23/SaleOfEquityShareUs112A/BalanceCG',
  'CG.LTCG_B4_Exemption': 'ScheduleCGFor23/LongTermCapGain23/SaleOfEquityShareUs112A/DeductionUs54F',
  'CG.LTCG_B6_Other': 'ScheduleCGFor23/LongTermCapGain23/SaleofAssetNADtls/SaleofAssetNA/CapgainonAssets',
  'CG.LTCG_B7_115AD': 'ScheduleCGFor23/LongTermCapGain23/NRISaleOfEquityShareUs112A/BalanceCG',
  'CG.LTCG_B9_Other': 'ScheduleCGFor23/LongTermCapGain23/NRIOnSec112and115/NRIOnSec112and115Dtls/CapgainonAssets',
  'CG.LTCG_B10_PTI': 'ScheduleCGFor23/LongTermCapGain23/PassThrIncNatureLTCG',
  'CG.LTCG_B11_DTAA': 'ScheduleCGFor23/LongTermCapGain23/TotalAmtTaxUsDTAALtcg',
  'CG.LTCG_B12_Total': 'ScheduleCGFor23/LongTermCapGain23/TotalLTCG',
  'CG.D_54EC': 'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54EC/AmtDeducted',
  'CG.D_54F': 'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54F/AmtDeducted',
  'CG.C1_TotalCG': 'ScheduleCGFor23/SumOfCGIncm',
  'CG.C2_VDA_CG': 'ScheduleCGFor23/IncmFromVDATrnsf',
  'CG.C3_Total': 'ScheduleCGFor23/TotScheduleCGFor23',
  'CG.F_Q1': 'ScheduleCGFor23/AccruOrRecOfCG/ShortTermUnder20Per/DateRange/Upto15Of6',
  'CG.F_Q2': 'ScheduleCGFor23/AccruOrRecOfCG/ShortTermUnder20Per/DateRange/Upto15Of9',
  'CG.F_Q3': 'ScheduleCGFor23/AccruOrRecOfCG/ShortTermUnder20Per/DateRange/Up16Of9To15Of12',
  'CG.F_Q4': 'ScheduleCGFor23/AccruOrRecOfCG/ShortTermUnder20Per/DateRange/Up16Of12To15Of3',
  'CG.F_Q5': 'ScheduleCGFor23/AccruOrRecOfCG/ShortTermUnder20Per/DateRange/Up16Of3To31Of3',
  'OS.Dividend1a': 'ScheduleOS/IncOthThanOwnRaceHorse/DividendGross',
  'OS.Interest1b': 'ScheduleOS/IncOthThanOwnRaceHorse/InterestGross',
  'OS.IntSavings': 'ScheduleOS/IncOthThanOwnRaceHorse/IntrstFrmSavingBank',
  'OS.IntDeposits': 'ScheduleOS/IncOthThanOwnRaceHorse/IntrstFrmTermDeposit',
  'OS.IntITRefund': 'ScheduleOS/IncOthThanOwnRaceHorse/IntrstFrmIncmTaxRefund',
  'OS.Rental1c': 'ScheduleOS/IncOthThanOwnRaceHorse/RentFromMachPlantBldgs',
  'OS.Income56_2x': 'ScheduleOS/IncOthThanOwnRaceHorse/Tot562x',
  'OS.FamilyPension': 'ScheduleOS/IncOthThanOwnRaceHorse/FamilyPension',
  'OS.Income89A_OS': 'ScheduleOS/IncOthThanOwnRaceHorse/IncomeNotified89AOS',
  'OS.Gross1': 'ScheduleOS/IncOthThanOwnRaceHorse/GrossIncChrgblTaxAtAppRate',
  'OS.Lottery2ai': 'ScheduleOS/IncOthThanOwnRaceHorse/LtryPzzlChrgblUs115BB',
  'OS.OnlineGames2aii': 'ScheduleOS/IncOthThanOwnRaceHorse/IncChrgblUs115BBJ',
  'OS.Unexplained2b': 'ScheduleOS/IncOthThanOwnRaceHorse/IncChrgblUs115BBE',
  'OS.AccumPF2c': 'ScheduleOS/IncOthThanOwnRaceHorse/TaxAccumulatedBalRecPF/TotalIncomeBenefit',
  'OS.AnySpecial2d': 'ScheduleOS/IncOthThanOwnRaceHorse/OthersGross',
  'OS.PTISpecial2e': 'ScheduleOS/IncOthThanOwnRaceHorse/PassThrIncOSChrgblSplRate',
  'OS.DTAA2f': 'ScheduleOS/IncOthThanOwnRaceHorse/IncChargblSplRateOS/TotalAmtTaxUsDTAASchOs',
  'OS.Ded57iia': 'ScheduleOS/IncOthThanOwnRaceHorse/Deductions/DeductionUs57iia',
  'OS.Ded57Exp': 'ScheduleOS/IncOthThanOwnRaceHorse/Deductions/Expenses',
  'OS.Ded57Int': 'ScheduleOS/IncOthThanOwnRaceHorse/Deductions/IntExp57',
  'OS.Dep3b': 'ScheduleOS/IncOthThanOwnRaceHorse/Deductions/Depreciation',
  'OS.Relief89A_5a': 'ScheduleOS/IncOthThanOwnRaceHorse/Increliefus89AOS',
  'OS.Net6': 'ScheduleOS/IncOthThanOwnRaceHorse/BalanceNoRaceHorse',
  'OS.Total7': 'ScheduleOS/TotOthSrcNoRaceHorse',
  'OS.RaceHorses8e': 'ScheduleOS/IncFromOwnHorse/BalanceOwnRaceHorse',
  'OS.Total9': 'ScheduleOS/IncChargeable',
  'OS.DivQ1': 'ScheduleOS/DividendIncUs115BBDA/DateRange/Upto15Of6',
  'OS.DivQ2': 'ScheduleOS/DividendIncUs115BBDA/DateRange/Up16Of6To15Of9',
  'OS.DivQ3': 'ScheduleOS/DividendIncUs115BBDA/DateRange/Up16Of9To15Of12',
  'OS.DivQ4': 'ScheduleOS/DividendIncUs115BBDA/DateRange/Up16Of12To15Of3',
  'OS.DivQ5': 'ScheduleOS/DividendIncUs115BBDA/DateRange/Up16Of3To31Of3',
  'CYLA.CYLA_HPLoss': 'ScheduleCYLA/TotalLossSetOff/TotHPlossCurYrSetoff',
  'CYLA.CYLA_BPLoss': 'ScheduleCYLA/TotalLossSetOff/TotBusLossSetoff',
  'CYLA.CYLA_OSLoss': 'ScheduleCYLA/TotalLossSetOff/TotOthSrcLossNoRaceHorseSetoff',
  'CYLA.BFLA_BFLoss': 'ScheduleBFLA/TotalBFLossSetOff/TotBFLossSetoff',
  'CYLA.BFLA_UnabsDep': 'ScheduleBFLA/TotalBFLossSetOff/TotUnabsorbedDeprSetoff',
  'CYLA.BFLA_Total': 'ScheduleBFLA/IncomeOfCurrYrAftCYLABFLA',
  'ICDS.ICDS_I': 'ScheduleICDS/AccPolicyAmtDetl/NetEffect',
  'ICDS.ICDS_II': 'ScheduleICDS/InventoriesValueDetl/NetEffect',
  'ICDS.ICDS_III': 'ScheduleICDS/ConstContractsAmtDetl/NetEffect',
  'ICDS.ICDS_IV': 'ScheduleICDS/RevenueRcgAmtDetl/NetEffect',
  'ICDS.ICDS_V': 'ScheduleICDS/TangibleFixedAssetDetl/NetEffect',
  'ICDS.ICDS_VI': 'ScheduleICDS/ForeignExgRatesDetl/NetEffect',
  'ICDS.ICDS_VII': 'ScheduleICDS/GovtGrantsDetl/NetEffect',
  'ICDS.ICDS_VIII': 'ScheduleICDS/SecuritiesDetl/NetEffect',
  'ICDS.ICDS_IX': 'ScheduleICDS/BorrowingCostsDetl/NetEffect',
  'ICDS.ICDS_X': 'ScheduleICDS/ProvAssetsDetl/NetEffect',
  'S10AA.UndertakingNo': 'Schedule10AA/DeductSEZ/DedUs10Detail/Undertaking/DedFromUndertakingWithAy/AssmtYrUnit',
  'S10AA.Amt10AA': 'Schedule10AA/DeductSEZ/DedUs10Detail/TotalDedUs10Sub',
  'D80D.SelfSenior': 'Schedule80D/Sec80DSelfFamSrCtznHealth/SeniorCitizenFlag',
  'D80D.SelfPremium': 'Schedule80D/Sec80DSelfFamSrCtznHealth/HealthInsPremSlfFam',
  'D80D.SelfCheckup': 'Schedule80D/Sec80DSelfFamSrCtznHealth/PrevHlthChckUpSlfFam',
  'D80D.SelfMedExp': 'Schedule80D/Sec80DSelfFamSrCtznHealth/MedicalExpSlfFamSrCtzn',
  'D80D.ParentSenior': 'Schedule80D/Sec80DSelfFamSrCtznHealth/ParentsSeniorCitizenFlag',
  'D80D.ParentPremium': 'Schedule80D/Sec80DSelfFamSrCtznHealth/HlthInsPremParents',
  'D80D.ParentCheckup': 'Schedule80D/Sec80DSelfFamSrCtznHealth/PrevHlthChckUpParents',
  'D80D.ParentMedExp': 'Schedule80D/Sec80DSelfFamSrCtznHealth/MedicalExpParentsSrCtzn',
  'D80D.Total80D': 'Schedule80D/Sec80DSelfFamSrCtznHealth/EligibleAmountOfDedn',
  'D80DD.DD_Category': 'Schedule80DD/NatureOfDisability',
  'D80DD.DD_NatureDisability': 'Schedule80DD/TypeOfDisability',
  'D80DD.DD_DependentType': 'Schedule80DD/DependentType',
  'D80DD.DD_DependentPAN': 'Schedule80DD/DependentPan',
  'D80DD.DD_Aadhaar': 'Schedule80DD/DependentAadhaar',
  'D80DD.U_Category': 'Schedule80U/NatureOfDisability',
  'D80DD.U_NatureDisability': 'Schedule80U/TypeOfDisability',
  'D80E.E_Interest': 'Schedule80E/TotalInterest80E',
  'D80E.EE_Interest': 'Schedule80EE/TotalInterest80EE',
  'D80E.EEA_Interest': 'Schedule80EEA/TotalInterest80EEA',
  'D80E.EEB_Interest': 'Schedule80EEB/TotalInterest80EEB',
  'VIA.VIA_80C': 'ScheduleVIA/DeductUndChapVIA/Section80C',
  'VIA.VIA_80CCC': 'ScheduleVIA/DeductUndChapVIA/Section80CCC',
  'VIA.VIA_80CCD1': 'ScheduleVIA/DeductUndChapVIA/Section80CCDEmployeeOrSE',
  'VIA.VIA_80CCD1B': 'ScheduleVIA/DeductUndChapVIA/Section80CCD1B',
  'VIA.VIA_80CCD2': 'ScheduleVIA/DeductUndChapVIA/Section80CCDEmployer',
  'VIA.VIA_PRAN': 'ScheduleVIA/UsrDeductUndChapVIA/PRANDtls/PRANNum',
  'VIA.VIA_80CCH': 'ScheduleVIA/DeductUndChapVIA/AnyOthSec80CCH',
  'VIA.VIA_80D': 'ScheduleVIA/DeductUndChapVIA/Section80D',
  'VIA.VIA_80DD': 'ScheduleVIA/DeductUndChapVIA/Section80DD',
  'VIA.VIA_80DDB': 'ScheduleVIA/DeductUndChapVIA/Section80DDB',
  'VIA.VIA_80DDB_Disease': 'ScheduleVIA/UsrDeductUndChapVIA/NameOfSpecDisease80DDB',
  'VIA.VIA_80E': 'ScheduleVIA/DeductUndChapVIA/Section80E',
  'VIA.VIA_80EE': 'ScheduleVIA/DeductUndChapVIA/Section80EE',
  'VIA.VIA_80EEA': 'ScheduleVIA/DeductUndChapVIA/Section80EEA',
  'VIA.VIA_80EEB': 'ScheduleVIA/DeductUndChapVIA/Section80EEB',
  'VIA.VIA_80G': 'ScheduleVIA/DeductUndChapVIA/Section80G',
  'VIA.VIA_80GG': 'ScheduleVIA/DeductUndChapVIA/Section80GG',
  'VIA.VIA_80GGA': 'ScheduleVIA/DeductUndChapVIA/Section80GGA',
  'VIA.VIA_80GGC': 'ScheduleVIA/DeductUndChapVIA/Section80GGC',
  'VIA.VIA_80IA': 'ScheduleVIA/DeductUndChapVIA/Section80IA',
  'VIA.VIA_80IB': 'ScheduleVIA/DeductUndChapVIA/Section80IB',
  'VIA.VIA_80IE': 'ScheduleVIA/DeductUndChapVIA/Section80IC',
  'VIA.VIA_80JJAA': 'ScheduleVIA/DeductUndChapVIA/Section80JJAA',
  'VIA.VIA_80QQB': 'ScheduleVIA/DeductUndChapVIA/Section80QQB',
  'VIA.VIA_80RRB': 'ScheduleVIA/DeductUndChapVIA/Section80RRB',
  'VIA.VIA_80TTA': 'ScheduleVIA/DeductUndChapVIA/Section80TTA',
  'VIA.VIA_80TTB': 'ScheduleVIA/DeductUndChapVIA/Section80TTB',
  'VIA.VIA_80U': 'ScheduleVIA/DeductUndChapVIA/Section80U',
  'VIA.VIA_PartB': 'ScheduleVIA/DeductUndChapVIA/TotPartBchapterVIA',
  'VIA.VIA_PartC': 'ScheduleVIA/DeductUndChapVIA/TotPartCchapterVIA',
  'VIA.VIA_Total': 'ScheduleVIA/DeductUndChapVIA/TotalChapVIADeductions',
  'AMT.AMT_TotalIncome': 'ScheduleAMT/TotalIncItem11',
  'AMT.AMT_PartCDed': 'ScheduleAMT/AdjustmentSec115JC/DeductClaimSec6A',
  'AMT.AMT_10AA': 'ScheduleAMT/AdjustmentSec115JC/DeductClaimSec10AA',
  'AMT.AMT_35AD': 'ScheduleAMT/AdjustmentSec115JC/DeductClaimSec35AD',
  'AMT.AMT_AdjTotal': 'ScheduleAMT/AdjustedUnderSec115JC',
  'AMT.AMT_Tax': 'ScheduleAMT/TaxPayableUnderSec115JC',
  'AMT.AMTC_BF': 'ScheduleAMTC/AmtTaxCreditAvailable',
  'AMT.AMTC_Utilized': 'ScheduleAMTC/TotAmtCreditUtilisedCY',
  'AMT.AMTC_CF': 'ScheduleAMTC/TotBalAMTCreditCF',
  'SPI.SI_Total': 'ScheduleSI/TotSplRateInc',
  'EI.EI_Interest': 'ScheduleEI/InterestInc',
  'EI.EI_AgriGross': 'ScheduleEI/GrossAgriRecpt',
  'EI.EI_AgriExp': 'ScheduleEI/ExpIncAgri',
  'EI.EI_AgriLossBF': 'ScheduleEI/UnabAgriLossPrev8',
  'EI.EI_AgriRule': 'ScheduleEI/AgriIncRule7and8',
  'EI.EI_AgriNet': 'ScheduleEI/NetAgriIncOrOthrIncRule7',
  'EI.EI_Other': 'ScheduleEI/Others',
  'EI.EI_DTAA': 'ScheduleEI/IncChrgblAsPerDTAA',
  'EI.EI_PTI': 'ScheduleEI/PassThrIncNotChrgblTax',
  'EI.EI_Total': 'ScheduleEI/TotalExemptInc',
  'S5A.SpousePAN5A': 'Schedule5A2014/PANOfSpouse',
  'S5A.HP5A': 'Schedule5A2014/HPHeadIncome/AmtApprndOfSpouse',
  'S5A.BP5A': 'Schedule5A2014/BusHeadIncome/AmtApprndOfSpouse',
  'S5A.CG5A': 'Schedule5A2014/CapGainHeadIncome/AmtApprndOfSpouse',
  'S5A.OS5A': 'Schedule5A2014/OtherSourcesHeadIncome/AmtApprndOfSpouse',
  'S5A.Tot5A': 'Schedule5A2014/TotalHeadIncome/AmtApprndOfSpouse',
  'AL.AL_Immovable': 'ScheduleAL/ImmovableDetails/Amount',
  'AL.AL_Jewellery': 'ScheduleAL/MovableAsset/JewelleryBullionEtc',
  'AL.AL_Vehicles': 'ScheduleAL/MovableAsset/VehiclYachtsBoatsAircrafts',
  'AL.AL_Bank': 'ScheduleAL/MovableAsset/DepositsInBank',
  'AL.AL_Shares': 'ScheduleAL/MovableAsset/SharesAndSecurities',
  'AL.AL_Insurance': 'ScheduleAL/MovableAsset/InsurancePolicies',
  'AL.AL_Loans': 'ScheduleAL/MovableAsset/LoansAndAdvancesGiven',
  'AL.AL_Cash': 'ScheduleAL/MovableAsset/CashInHand',
  'AL.AL_Liability': 'ScheduleAL/LiabilityInRelatAssets',
  'ESOP.ESOP_TaxCF': 'ScheduleESOP/ScheduleESOP2627_Type/BalanceTaxCF',
  'TPSA.TPSA_Primary': 'ScheduleTPSA/AmtPrimaryAdjUs92CE_2A',
  'TPSA.TPSA_Tax18': 'ScheduleTPSA/AdditionalIncTax18PercAbove',
  'TPSA.TPSA_Surch': 'ScheduleTPSA/Surcharge12Perc',
  'TPSA.TPSA_Cess': 'ScheduleTPSA/HealthEducationCess',
  'TPSA.TPSA_TotalTax': 'ScheduleTPSA/TotalAdditionalTax',
  'TPSA.TPSA_Paid': 'ScheduleTPSA/TaxesPaid',
  'TPSA.TPSA_Net': 'ScheduleTPSA/NetTaxPayable',
  'BTI.TI_Salary': 'PartB-TI/Salaries',
  'BTI.TI_HP': 'PartB-TI/IncomeFromHP',
  'BTI.TI_PGBP': 'PartB-TI/ProfBusGain/TotProfBusGain',
  'BTI.TI_STCG': 'PartB-TI/CapGain/ShortTerm/TotalShortTerm',
  'BTI.TI_LTCG': 'PartB-TI/CapGain/LongTerm/TotalLongTerm',
  'BTI.TI_CG': 'PartB-TI/CapGain/TotalCapGains',
  'BTI.TI_OS': 'PartB-TI/IncFromOS/TotIncFromOS',
  'BTI.TI_Total6': 'PartB-TI/TotalTI',
  'BTI.TI_CYLA': 'PartB-TI/CurrentYearLoss',
  'BTI.TI_BFLA': 'PartB-TI/BroughtFwdLossesSetoff',
  'BTI.TI_GTI': 'PartB-TI/GrossTotalIncome',
  'BTI.TI_SpecialInGTI': 'PartB-TI/IncChargeTaxSplRate111A112',
  'BTI.TI_VIA_a': 'PartB-TI/DeductionsUndSchVIADtl/PartBchapterVIA',
  'BTI.TI_VIA_b': 'PartB-TI/DeductionsUndSchVIADtl/PartCchapterVIA',
  'BTI.TI_10AA': 'PartB-TI/DeductionsUnder10Aor10AA',
  'BTI.TI_TotalIncome': 'PartB-TI/TotalIncome',
  'BTI.TI_SpecialIncome': 'PartB-TI/IncChargeableTaxSplRates',
  'BTI.TI_NetAgri': 'PartB-TI/NetAgricultureIncomeOrOtherIncomeForRate',
  'BTI.TI_AggIncome': 'PartB-TI/AggregateIncome',
  'BTI.TI_CFLosses': 'PartB-TI/LossesOfCurrentYearCarriedFwd',
  'BTI.TI_DeemedAMT': 'PartB-TI/DeemedIncomeUs115JC',
  'BTTI.TTI_TaxNormal': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/TaxAtNormalRatesOnAggrInc',
  'BTTI.TTI_TaxSpecial': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/TaxAtSpecialRates',
  'BTTI.TTI_AgriRebate': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/RebateOnAgriInc',
  'BTTI.TTI_TaxPayable1d': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/TaxPayableOnTotInc',
  'BTTI.TTI_TaxAMT': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnDeemedTI/TotalTax',
  'BTTI.TTI_Rebate87A': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/Rebate87A',
  'BTTI.TTI_GrossTax': 'PartB_TTI/ComputationOfTaxLiability/GrossTaxPayable',
  'BTTI.TTI_AMTCredit': 'PartB_TTI/ComputationOfTaxLiability/CreditUS115JD',
  'BTTI.TTI_Surcharge': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/TotalSurcharge',
  'BTTI.TTI_Cess': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/EducationCess',
  'BTTI.TTI_GrossLiab': 'PartB_TTI/ComputationOfTaxLiability/TaxPayableOnTI/GrossTaxLiability',
  'BTTI.TTI_Relief89': 'PartB_TTI/ComputationOfTaxLiability/TaxRelief/Section89',
  'BTTI.TTI_Relief90': 'PartB_TTI/ComputationOfTaxLiability/TaxRelief/Section90',
  'BTTI.TTI_Relief91': 'PartB_TTI/ComputationOfTaxLiability/TaxRelief/Section91',
  'BTTI.TTI_NetLiab': 'PartB_TTI/ComputationOfTaxLiability/NetTaxLiability',
  'BTTI.TTI_234A': 'PartB_TTI/ComputationOfTaxLiability/IntrstPay/IntrstPayUs234A',
  'BTTI.TTI_234B': 'PartB_TTI/ComputationOfTaxLiability/IntrstPay/IntrstPayUs234B',
  'BTTI.TTI_234C': 'PartB_TTI/ComputationOfTaxLiability/IntrstPay/IntrstPayUs234C',
  'BTTI.TTI_234F': 'PartB_TTI/ComputationOfTaxLiability/IntrstPay/LateFilingFee234F',
  'BTTI.TTI_234I': 'PartB_TTI/ComputationOfTaxLiability/IntrstPay/FeeFurnish234I',
  'BTTI.TTI_AggLiab': 'PartB_TTI/ComputationOfTaxLiability/AggregateTaxInterestLiability',
  'BTTI.TTI_TotalPaid': 'PartB_TTI/TaxPaid/TaxesPaid/TotalTaxesPaid',
  'BTTI.TTI_Payable': 'PartB_TTI/TaxPaid/BalTaxPayable',
  'BTTI.TTI_Refund': 'PartB_TTI/Refund/RefundDue',
  'BTTI.TTI_FAFlag': 'PartB_TTI/AssetOutIndiaFlag',
  'VER.VerName': 'Verification/Declaration/AssesseeVerName',
  'VER.VerFatherName': 'Verification/Declaration/FatherName',
  'VER.VerPAN': 'Verification/Declaration/AssesseeVerPAN',
  'VER.VerCapacity': 'Verification/Capacity',
  'VER.VerPlace': 'Verification/Place',
  'VER.VerDate': 'Verification/Date',
};

/** One repeating block of a table: the array path and its column-to-node map. */
export interface TableGroup {
  array: string;
  cols: Readonly<Record<string, string>>;
}

/**
 * How a table's rows land in the return body. A table may feed more than one
 * block — Schedule HP writes co-owners and tenants into arrays nested inside the
 * property array — and `orphan` holds columns whose target is decided by
 * SCH_ROUTES rather than by position.
 */
export interface TableMap {
  sheet: string;
  groups: readonly TableGroup[];
  orphan: Readonly<Record<string, string>>;
}

/** Table key to its repeating blocks in the return body. */
export const SCH_TABLES: Readonly<Record<string, TableMap>> = {
  UnlistedShares: {
    sheet: 'GEN',
    groups: [
    {
      array: 'PartA_GEN1/FilingStatus/HeldUnlistedEqShrPrYr/HeldUnlistedEqShrPrYrDtls',
      cols: {
        CompanyName: 'NameOfCompany',
        CompanyPAN: 'PAN',
        CompanyType: 'CompanyType',
        OpeningShares: 'OpngBalNumberOfShares',
        OpeningCost: 'OpngBalCostOfAcquisition',
        AcqShares: 'ShrAcqDurYrNumberOfShares',
        AcqCost: 'PurchasePricePerShare',
        IssuePrice: 'IssuePricePerShare',
        TransferShares: 'ShrTrnfNumberOfShares',
        SaleConsid: 'ShrTrnfSaleConsideration',
        ClosingShares: 'ClsngBalNumberOfShares',
        ClosingCost: 'ClsngBalCostOfAcquisition',
      },
    },
    ],
    orphan: {},
  },
  Directorship: {
    sheet: 'GEN',
    groups: [
    {
      array: 'PartA_GEN1/FilingStatus/CompDirectorPrvYr/CompDirectorPrvYrDtls',
      cols: {
        CoName: 'NameOfCompany',
        CoType: 'CompanyType',
        CoPAN: 'PAN',
        DIN: 'DIN',
        SharesListed: 'SharesTypes',
      },
    },
    ],
    orphan: {},
  },
  NOBRows: {
    sheet: 'NOB',
    groups: [
    {
      array: 'PartA_GEN2/NatOfBus/NatureOfBusiness',
      cols: {
        Code: 'Code',
        TradeName: 'TradeName1',
        Description: 'Description',
      },
    },
    ],
    orphan: {},
  },
  Goods44AE: {
    sheet: 'PL',
    groups: [
    {
      array: 'PARTA_PL/GoodsDtlsUs44AE',
      cols: {
        RegNo: 'RegNumberGoodsCarriage',
        Ownership: 'OwnedLeasedHiredFlag',
        Tonnage: 'TonnageCapacity',
        Months: 'HoldingPeriod',
        PresInc: 'PresumptiveIncome',
      },
    },
    ],
    orphan: {},
  },
  BadDebtors: {
    sheet: 'PL',
    groups: [
    {
      array: 'PARTA_PL/DebitsToPL/BadDebtDtls/BadDebtAmtDtls',
      cols: {
        DebtorPAN: 'PAN',
        Amt: 'Amount',
      },
    },
    {
      array: 'PARTA_PL/DebitsToPL/BadDebtDtls/OthersPANNotAvlblDtl',
      cols: {
        DebtorName: 'Name',
      },
    },
    ],
    orphan: {},
  },
  HPRows: {
    sheet: 'HP',
    groups: [
    {
      array: 'ScheduleHP/PropertyDetails',
      cols: {
        Address: 'AddressDetailWithZipCode/AddrDetail',
        Type: 'ifLetOut',
        CoOwned: 'PropCoOwnedFlg',
        OwnShare: 'AsseseeShareProperty',
        GrossRent: 'Rentdetails/AnnualLetableValue',
        UnrealRent: 'Rentdetails/RentNotRealized',
        MunTax: 'Rentdetails/LocalTaxes',
        AnnualValue: 'Rentdetails/BalanceALV',
        StdDed30: 'Rentdetails/ThirtyPercentOfBalance',
        Interest24b: 'Rentdetails/IntOnBorwCap',
        ArrearsRent: 'Rentdetails/ArrearsUnrealizedRentRcvd',
        IncomeHP: 'Rentdetails/IncomeOfHP',
      },
    },
    {
      array: 'ScheduleHP/PropertyDetails/CoOwners',
      cols: {
        CoOwnerPAN: 'PAN_CoOwner',
      },
    },
    {
      array: 'ScheduleHP/PropertyDetails/TenantDetails',
      cols: {
        TenantName: 'NameofTenant',
      },
    },
    ],
    orphan: {},
  },
  Sch112A: {
    sheet: 'CG',
    groups: [
    {
      array: 'Schedule112A/Schedule112ADtls',
      cols: {
        ISIN: 'ISINCode',
        ShareName: 'ShareUnitName',
        Qty: 'NumSharesUnits',
        SalePrice: 'SalePricePerShareUnit',
        SaleValue: 'TotSaleValue',
        CostNoIndex: 'CostAcqWithoutIndx',
        FMV31Jan18: 'TotFairMktValueCapAst',
        Expense: 'ExpExclCnctTransfer',
        Balance: 'Balance',
      },
    },
    ],
    orphan: {},
  },
  VDARows: {
    sheet: 'VDA',
    groups: [
    {
      array: 'ScheduleVDA/ScheduleVDADtls',
      cols: {
        DateAcq: 'DateofAcquisition',
        DateTrf: 'DateofTransfer',
        Head: 'HeadUndIncTaxed',
        CostAcq: 'AcquisitionCost',
        Consideration: 'ConsidReceived',
        Income: 'IncomeFromVDA',
      },
    },
    ],
    orphan: {},
  },
  CFLRows: {
    sheet: 'CFL',
    groups: [],
    orphan: {
      FilingDate: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/DateOfFiling',
      HPLoss: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/TotalHPPTILossCF',
      BPLoss: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/BusLossOthThanSpecLossCF',
      SpecLoss: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/LossFrmSpecBusCF',
      SpecifiedLoss: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/LossFrmSpecifiedBusCF',
      STCL: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/TotalSTCGPTILossCF',
      LTCL: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/TotalLTCGPTILossCF',
      RaceLoss: 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail/OthSrcLossRaceHorseCF',
    },
  },
  UDRows: {
    sheet: 'UD',
    groups: [
    {
      array: 'ITR3ScheduleUD/ScheduleUD',
      cols: {
        AY: 'AssYr',
        DepBF: 'AmtBFUD',
        Adj115BAC: 'AdjustAccTax115BACAmt',
        SetOff: 'AmtDeprSOCY',
        DepCF: 'BalCFNY',
      },
    },
    ],
    orphan: {},
  },
  Rows80G: {
    sheet: 'D80G',
    groups: [
    {
      array: 'Schedule80G/Don100Percent/DoneeWithPan',
      cols: {
        DoneeName: 'DoneeWithPanName',
        DoneePAN: 'DoneePAN',
        Address: 'AddressDetail/AddrDetail',
        Cash: 'DonationAmtCash',
        Other: 'DonationAmtOtherMode',
        RefNo: 'TransactionRefNum',
        Total: 'DonationAmt',
        Eligible: 'EligibleDonationAmt',
      },
    },
    {
      array: 'Schedule80G/Don50PercentApprReqd/DoneeWithPan',
      cols: {
        ARN: 'ArnNbr',
      },
    },
    ],
    orphan: {},
  },
  Rows80GGA: {
    sheet: 'D80GGA',
    groups: [
    {
      array: 'Schedule80GGA/DonationDtlsSciRsrchRuralDev',
      cols: {
        Section: 'RelevantClauseUndrDedClaimed',
        DoneeName: 'NameOfDonee',
        DoneePAN: 'DoneePAN',
        Cash: 'DonationAmtCash',
        Other: 'DonationAmtOtherMode',
        Total: 'DonationAmt',
        Eligible: 'EligibleDonationAmt',
      },
    },
    ],
    orphan: {},
  },
  Rows80GGC: {
    sheet: 'D80GGC',
    groups: [
    {
      array: 'Schedule80GGC/Schedule80GGCDetails',
      cols: {
        Date: 'DonationDate',
        PartyName: 'PoliticalPartyName',
        PartyPAN: 'PoliticalPartyPAN',
        Cash: 'DonationAmtCash',
        Other: 'DonationAmtOtherMode',
        RefNo: 'TransactionRefNum',
        Total: 'DonationAmt',
        Eligible: 'EligibleDonationAmt',
      },
    },
    ],
    orphan: {},
  },
  Rows80C: {
    sheet: 'D80C',
    groups: [
    {
      array: 'Schedule80C/Schedule80CDtls',
      cols: {
        PolicyNo: 'IdentificationNo',
        Amount: 'Amount',
      },
    },
    ],
    orphan: {},
  },
  RARows: {
    sheet: 'RA',
    groups: [
    {
      array: 'Schedule80RA/DonationDtlsRsrchAssctn',
      cols: {
        Name: 'NameOfDonee',
        PAN: 'DoneePAN',
        Cash: 'DonationAmtCash',
        Other: 'DonationAmtOtherMode',
        Total: 'DonationAmt',
        Eligible: 'EligibleDonationAmt',
      },
    },
    ],
    orphan: {},
  },
  IFRows: {
    sheet: 'SPI',
    groups: [
    {
      array: 'ScheduleIF/PartnerFirmDetails',
      cols: {
        FirmName: 'FirmName',
        FirmPAN: 'FirmPAN',
        Liable92E_IF: 'IsLiableToAudit',
        PctShare: 'ProfitSharePercent',
        ShareAmt: 'ProfitShareAmt',
        Capital: 'FirmCapBalOn31Mar',
        InterestRecd: 'IntrstAmtDueOrRecv',
        RemunRecd: 'RemunernAmtDueOrRecv',
      },
    },
    ],
    orphan: {},
  },
  PTIRows: {
    sheet: 'PTI',
    groups: [
    {
      array: 'SchedulePTI/SchedulePTIDtls',
      cols: {
        FundName: 'BusinessName',
        FundPAN: 'BusinessPAN',
        HeadInc: 'InvstmntCvrdUs115UA115UB',
        Amount: 'IncFromHP/AmountOfInc',
        TDSAmt: 'IncFromHP/TDSAmount',
      },
    },
    ],
    orphan: {},
  },
  FSIRows: {
    sheet: 'FSI',
    groups: [
    {
      array: 'ScheduleFSI/ScheduleFSIDtls',
      cols: {
        IncomeFrgn: 'TotalCountryWise/IncFrmOutsideInd',
        TaxPaidFrgn: 'TotalCountryWise/TaxPaidOutsideInd',
        TaxPayableIN: 'TotalCountryWise/TaxPayableinInd',
        ReliefE: 'TotalCountryWise/TaxReliefinInd',
      },
    },
    {
      array: 'ScheduleTR1/ScheduleTR',
      cols: {
        Section: 'ReliefClaimedUsSection',
      },
    },
    ],
    orphan: {},
  },
  FARows: {
    sheet: 'FA',
    groups: [
    {
      array: 'ScheduleFA/DetailsForiegnBank',
      cols: {
        AccountNo: 'ForeignAccountNumber',
        OpenDate: 'AccOpenDate',
        PeakBal: 'PeakBalanceDuringYear',
        CloseBal: 'ClosingBalance',
        IncomeAccrued: 'IntrstAccured',
      },
    },
    ],
    orphan: {},
  },
  GSTRows: {
    sheet: 'GSTS',
    groups: [
    {
      array: 'ScheduleGST/TurnoverGrsRcptForGSTIN',
      cols: {
        GSTIN: 'GSTINNo',
        Turnover: 'AmtTurnGrossRcptGSTIN',
      },
    },
    ],
    orphan: {},
  },
  BankRows: {
    sheet: 'BTTI',
    groups: [
    {
      array: 'PartB_TTI/Refund/BankAccountDtls/AddtnlBankDetails',
      cols: {
        IFSC: 'IFSCCode',
        BankName: 'BankName',
        AccountNo: 'BankAccountNo',
        Nominate: 'UseForRefund',
      },
    },
    ],
    orphan: {},
  },
  TDS1Rows: {
    sheet: 'TDS1',
    groups: [
    {
      array: 'ScheduleTDS1/TDSonSalary',
      cols: {
        TAN: 'EmployerOrDeductorOrCollectDetl/TAN',
        EmpName: 'EmployerOrDeductorOrCollectDetl/EmployerOrDeductorOrCollecterName',
        IncomeSal: 'IncChrgSal',
        TaxDeducted: 'TotalTDSSal',
      },
    },
    ],
    orphan: {},
  },
  TDS2Rows: {
    sheet: 'TDS2',
    groups: [
    {
      array: 'ScheduleTDS2/TDSOthThanSalaryDtls',
      cols: {
        TAN2: 'TANOfDeductor',
        DeductorName: 'TDSCreditName',
        TDSDeducted: 'TaxDeductCreditDtls/TaxDeductedOwnHands',
        TDSClaimed: 'TaxDeductCreditDtls/TaxClaimedOwnHands',
        GrossAmt: 'GrossAmount',
        HeadIncome: 'HeadOfIncome',
        TDSCF: 'AmtCarriedFwd',
      },
    },
    ],
    orphan: {},
  },
  TDS3Rows: {
    sheet: 'TDS3',
    groups: [
    {
      array: 'ScheduleTDS3/TDS3onOthThanSalDtls',
      cols: {
        TenantPAN: 'PANOfBuyerTenant',
        TenantName: 'TDSCreditName',
        TDSDed3: 'TaxDeductCreditDtls/TaxDeductedOwnHands',
        TDSClm3: 'TaxDeductCreditDtls/TaxClaimedOwnHands',
        GrossRentAmt: 'GrossAmount',
      },
    },
    ],
    orphan: {},
  },
  TCSRows: {
    sheet: 'TCS',
    groups: [
    {
      array: 'ScheduleTCS/TCS',
      cols: {
        CollectorTAN: 'EmployerOrDeductorOrCollectTAN',
        CollectorName: 'TCSCreditOwner',
        TCSCollected: 'TCSCurrFYDtls/TCSAmtCollOwnHand',
        TCSClaimed: 'TCSClaimedThisYearDtls/TCSAmtCollOwnHand',
        TCSCF: 'AmtCarriedFwd',
      },
    },
    ],
    orphan: {},
  },
  ITRows: {
    sheet: 'IT',
    groups: [
    {
      array: 'ScheduleIT/TaxPayment',
      cols: {
        BSRCode: 'BSRCode',
        DepDate: 'DateDep',
        ChallanNo: 'SrlNoOfChaln',
        TaxAmt: 'Amt',
      },
    },
    ],
    orphan: {},
  },
};

/**
 * A table whose rows are split across several targets by the value of one
 * column — the 80G block letter, the assessment year of a carried-forward loss,
 * whether a bad debt carries a PAN.
 */
export interface TableRoute {
  by: string;
  mode: 'array' | 'object';
  targets: Readonly<Record<string, string>>;
}

/** Tables routed row by row. */
export const SCH_ROUTES: Readonly<Record<string, TableRoute>> = {
  Rows80G: {
    by: 'Block',
    mode: 'array',
    targets: {
      '100% without qualifying limit': 'Schedule80G/Don100Percent/DoneeWithPan',
      '50% without qualifying limit': 'Schedule80G/Don50PercentNoApprReqd/DoneeWithPan',
      '100% with qualifying limit': 'Schedule80G/Don100PercentApprReqd/DoneeWithPan',
      '50% with qualifying limit': 'Schedule80G/Don50PercentApprReqd/DoneeWithPan',
    },
  },
  CFLRows: {
    by: 'AY',
    mode: 'object',
    targets: {
      '2018-19': 'ScheduleCFL/LossCFFromPrev8thYearFromAY/CarryFwdLossDetail',
      '2019-20': 'ScheduleCFL/LossCFFromPrev7thYearFromAY/CarryFwdLossDetail',
      '2020-21': 'ScheduleCFL/LossCFFromPrev6thYearFromAY/CarryFwdLossDetail',
      '2021-22': 'ScheduleCFL/LossCFCurrentAssmntYear2021/CarryFwdLossDetail',
      '2022-23': 'ScheduleCFL/LossCFCurrentAssmntYear2022/CarryFwdLossDetail',
      '2023-24': 'ScheduleCFL/LossCFCurrentAssmntYear2023/CarryFwdLossDetail',
      '2024-25': 'ScheduleCFL/LossCFCurrentAssmntYear2024/CarryFwdLossDetail',
      '2025-26': 'ScheduleCFL/LossCFCurrentAssmntYear2025/CarryFwdLossDetail',
      '2026-27': 'ScheduleCFL/LossCFCurrentAssmntYear2026/CarryFwdLossDetail',
    },
  },
  BadDebtors: {
    by: '__pan__',
    mode: 'array',
    targets: {
      withPAN: 'PARTA_PL/DebitsToPL/BadDebtDtls/BadDebtAmtDtls',
      withoutPAN: 'PARTA_PL/DebitsToPL/BadDebtDtls/OthersPANNotAvlblDtl',
    },
  },
};

/**
 * Scalar fields whose path runs through a repeating block. The builder creates a
 * single entry at this array path and writes the field's leaf node inside it.
 */
export const SCH_SCALAR_IN_ARRAY: Readonly<Record<string, string>> = {
  'GEN.JurisdictionResidence': 'PartA_GEN1/FilingStatus/JurisdictionResPrevYr/JurisdictionResPrevYrDtls',
  'PL.OthPresSec': 'PARTA_PL/NonResidentPLDetails',
  'PL.OthPresGR': 'PARTA_PL/NonResidentPLDetails',
  'PL.OthPresNP': 'PARTA_PL/NonResidentPLDetails',
  'S.EmployerName': 'ScheduleS/Salaries',
  'S.EmployerTAN': 'ScheduleS/Salaries',
  'S.EmployerCategory': 'ScheduleS/Salaries',
  'S.Sal17_1': 'ScheduleS/Salaries',
  'S.Perq17_2': 'ScheduleS/Salaries',
  'S.Profit17_3': 'ScheduleS/Salaries',
  'S.Income89A_1d': 'ScheduleS/Salaries',
  'S.Income89A_1e': 'ScheduleS/Salaries',
  'BP.SpecifiedNature': 'ITR3ScheduleBP/SpecifiedBusinessInc/DedUs35ADSubSec5Dtls',
  'CG.STCG_A1_LandBld': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.STCG_A1_Cost': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.STCG_A1_Improve': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.STCG_A1_Exp': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.STCG_A1e': 'ScheduleCGFor23/ShortTermCapGainFor23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.STCG_A3_111A': 'ScheduleCGFor23/ShortTermCapGainFor23/EquityMFonSTT',
  'CG.LTCG_B1_LandBld': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.LTCG_B1_IndexCost': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.LTCG_B1_PurDate': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.LTCG_B1_SaleDate': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.LTCG_B1e': 'ScheduleCGFor23/LongTermCapGain23/SaleofLandBuild/SaleofLandBuildDtls',
  'CG.LTCG_B3_Bonds': 'ScheduleCGFor23/LongTermCapGain23/Proviso112Applicable',
  'CG.LTCG_B9_Other': 'ScheduleCGFor23/LongTermCapGain23/NRIOnSec112and115/NRIOnSec112and115Dtls',
  'CG.D_54EC': 'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54EC',
  'CG.D_54F': 'ScheduleCGFor23/DeducClaimInfo/DeducClaimDtlsUs54F',
  'S10AA.UndertakingNo': 'Schedule10AA/DeductSEZ/DedUs10Detail/Undertaking/DedFromUndertakingWithAy',
  'VIA.VIA_PRAN': 'ScheduleVIA/UsrDeductUndChapVIA/PRANDtls',
  'SPI.SI_111A': 'ScheduleSI/SplCodeRateTax',
  'SPI.SI_112A': 'ScheduleSI/SplCodeRateTax',
  'SPI.SI_115BB': 'ScheduleSI/SplCodeRateTax',
  'SPI.SI_115BBJ': 'ScheduleSI/SplCodeRateTax',
  'SPI.SI_115BBE': 'ScheduleSI/SplCodeRateTax',
  'SPI.SI_115BBH': 'ScheduleSI/SplCodeRateTax',
  'AL.AL_Immovable': 'ScheduleAL/ImmovableDetails',
};

/**
 * Departmental codes for every select field, keyed by the wording the prototype
 * shows. ITR3_SCHEDULES carries the code as the option value, so the builder can
 * take a stored value straight through; this map is what decodes a value that
 * was captured as wording.
 */
export const SCH_ENUM: Readonly<Record<string, Readonly<Record<string, string | number>>>> = {
  'GEN.Status': {
    'I — Individual': 'I',
    'H — Hindu Undivided Family': 'H',
  },
  'GEN.ResidentialStatus': {
    'RES — Resident': 'RES',
    'NOR — Resident but not ordinarily resident': 'NOR',
    'NRI — Non-resident': 'NRI',
  },
  'GEN.ReturnFileSec': {
    '139(1) — on or before the due date': 11,
    '139(4) — belated': 12,
    '139(5) — revised': 17,
    '139(9) — in response to defective notice': 18,
    '142(1) — in response to notice': 13,
    '148 — reassessment': 14,
    '119(2)(b) — condonation': 20,
    '92CD — modified return': 19,
    '139(8A) — updated return': 21,
  },
  'GEN.DueDate': {
    '31st July': '31ST JULY',
    '31st October': '31ST OCTOBER',
    '30th November': '30TH NOVEMBER',
  },
  'GEN.TurnoverRange': {
    'Up to ₹1 crore': 'Upto1CR',
    'More than ₹1 crore and up to ₹10 crore': 'Upto10CR',
    'More than ₹10 crore': 'MoreThan10CR',
  },
  'GEN.CashReceiptPct': {
    'Up to 5%': 'Upto5Per',
    'More than 5%': 'MoreThan5Per',
  },
  'GEN.CashPaymentPct': {
    'Up to 5%': 'Upto5Per',
    'More than 5%': 'MoreThan5Per',
  },
  'GEN.Audit44ABCondition': {
    'Sales or turnover exceeding ₹1 crore': 'bi',
    'Turnover up to ₹10 crore with cash receipts or payments exceeding 5%': 'bi',
    'Turnover exceeding ₹10 crore': 'bi',
    'Profit declared below the limit under section 44AD(4)': 'bii',
    'Profit declared below 50% under section 44ADA': 'bii',
    'Other': 'biii',
  },
  'GEN.OptOutNewTaxRegime': {
    'No — new tax regime applies': 'N',
    'Yes — opting for the old regime': 'Y',
    'Continuing to opt out': 'Y',
    'Re-entering the new regime': 'N',
  },
  'OI.MethodAcc': {
    'Mercantile': 'MERC',
    'Cash': 'CASH',
  },
  'OI.MethodValStock': {
    'Cost': '2',
    'Market rate': '3',
    'Cost or market rate, whichever is lower': '1',
  },
  'S.EmployerCategory': {
    'Central Government': 'CGOV',
    'State Government': 'SGOV',
    'Public Sector Undertaking': 'PSU',
    'Pensioners — Central Government': 'PE',
    'Pensioners — State Government': 'PESG',
    'Pensioners — Public Sector Undertaking': 'PEPS',
    'Pensioners — Other': 'PEO',
    'Others': 'OTH',
    'Not applicable': '',
  },
  'S.HRAMetro': {
    'Metro city — fifty per cent': '1',
    'Non-metro city — forty per cent': '2',
  },
  'D80D.SelfSenior': {
    'No': 'N',
    'Yes': 'Y',
    'Not claiming for self or family': 'S',
  },
  'D80D.ParentSenior': {
    'No': 'N',
    'Yes': 'Y',
    'Not claiming for parents': 'S',
  },
  'D80DD.DD_Category': {
    'Not applicable': '',
    'Dependant with disability — ₹75,000': '1',
    'Dependant with severe disability — ₹1,25,000': '2',
  },
  'D80DD.U_Category': {
    'Not applicable': '',
    'Self with disability — ₹75,000': '1',
    'Self with severe disability — ₹1,25,000': '2',
  },
  'VER.VerCapacity': {
    'Self': 'S',
    'Karta': 'K',
    'Representative assessee': 'R',
    'Authorised signatory': 'A',
  },
  'PL.OthPresSec': {
    'Not applicable': '',
    '44B — seven and one-half per cent': '44B',
    '44BB — ten per cent': '44BB',
    '44BBA — five per cent': '44BBA',
    '44BBC — twenty per cent': '44BBC',
    '44BBD — twenty-five per cent': '44BBD',
  },
  'ESOP.ESOP_Sold': {
    'Not sold': 'N',
    'Partly sold': 'Y',
    'Fully sold': 'Y',
  },
  'GEN.SecAddSame': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.BusIncomeFlag': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.SeventhProviso139': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.LiableAudit44AB': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.AuditedFlag': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.Liable92E': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.PresumptiveOnly': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.FPIFlag': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.PortugueseCC': {
    'Yes': 'Y',
    'No': 'N',
  },
  'GEN.RepAssesseeFlag': {
    'Yes': 'Y',
    'No': 'N',
  },
  'OI.MethodChange': {
    'Yes': 'Y',
    'No': 'N',
  },
  'OI.Sec92CE2A': {
    'Yes': 'Y',
    'No': 'N',
  },
  'BTTI.TTI_FAFlag': {
    'Yes': 'Y',
    'No': 'N',
  },
};

/** Schedule SI section code and the rate at which that income is charged. */
export interface SpecialRateCode {
  SecCode: string;
  SplRatePercent: number;
}

/** Schedule SI rows, keyed by the field that carries the amount. */
export const SCH_SI: Readonly<Record<string, SpecialRateCode>> = {
  'SPI.SI_111A': { SecCode: '1A', SplRatePercent: 20 },
  'SPI.SI_112A': { SecCode: '22', SplRatePercent: 12.5 },
  'SPI.SI_115BB': { SecCode: '5BB', SplRatePercent: 30 },
  'SPI.SI_115BBJ': { SecCode: '5BBJ', SplRatePercent: 30 },
  'SPI.SI_115BBE': { SecCode: '5BBE', SplRatePercent: 60 },
  'SPI.SI_115BBH': { SecCode: '5BBH', SplRatePercent: 30 },
};

/** Fields the builder writes as a date. */
export const SCH_DATE: ReadonlySet<string> = new Set([
  'CFL.FilingDate',
  'CG.LTCG_B1_PurDate',
  'CG.LTCG_B1_SaleDate',
  'D80GGC.Date',
  'FA.OpenDate',
  'GEN.AuditFurnishDate',
  'GEN.AuditReportDate',
  'GEN.DOB',
  'GEN.DOCB',
  'GEN.Form10IEADate',
  'GEN.NoticeDate',
  'GEN.OrigRetDate',
  'IT.DepDate',
  'VDA.DateAcq',
  'VDA.DateTrf',
  'VER.VerDate',
]);

/** Fields the builder writes as a number rather than a string. */
export const SCH_NUM: ReadonlySet<string> = new Set([
  'AL.AL_Bank',
  'AL.AL_Cash',
  'AL.AL_Immovable',
  'AL.AL_Insurance',
  'AL.AL_Jewellery',
  'AL.AL_Liability',
  'AL.AL_Loans',
  'AL.AL_Shares',
  'AL.AL_Vehicles',
  'AMT.AMTC_BF',
  'AMT.AMTC_CF',
  'AMT.AMTC_Utilized',
  'AMT.AMT_10AA',
  'AMT.AMT_35AD',
  'AMT.AMT_AdjTotal',
  'AMT.AMT_PartCDed',
  'AMT.AMT_Tax',
  'AMT.AMT_TotalIncome',
  'BP.A10',
  'BP.A11_Depreciation',
  'BP.A12i_DepIT',
  'BP.A12ii_Dep32_1i',
  'BP.A13',
  'BP.A14_Dis36',
  'BP.A15_Dis37',
  'BP.A16_Dis40',
  'BP.A17_Dis40A',
  'BP.A18_Dis43B',
  'BP.A1_ProfitPL',
  'BP.A22_Interest23',
  'BP.A24e_ESRNeg',
  'BP.A25_ICDSInc',
  'BP.A26',
  'BP.A27_43BAllow',
  'BP.A28_ESRDeduction',
  'BP.A2a_SpecProfit',
  'BP.A2b_SpecifiedProfit',
  'BP.A32_ICDSDec',
  'BP.A33',
  'BP.A34_Income',
  'BP.A35i_44AD',
  'BP.A35ii_44ADA',
  'BP.A35iii_44AE',
  'BP.A35iv_vii',
  'BP.A36_NetPGBP',
  'BP.A37',
  'BP.A38_AgriDeemed',
  'BP.A3a_SalaryInc',
  'BP.A3b_HPInc',
  'BP.A3c_CGInc',
  'BP.A3d_OSInc',
  'BP.A3e_115BBF',
  'BP.A3f_115BBG',
  'BP.A3g_115BBH',
  'BP.A4a_ExemptInc',
  'BP.A4b_Rule7',
  'BP.A5a_FirmShare',
  'BP.A5c_DividendRed',
  'BP.A6_Balance',
  'BP.A9_Additions',
  'BP.B39_SpecPL',
  'BP.B42_SpecIncome',
  'BP.C43_SpecifiedPL',
  'BP.C48_SpecifiedIncome',
  'BP.D_TotalPGBP',
  'BS.AdvFrom40A2b',
  'BS.AdvFromOthers',
  'BS.ApplicationTotal',
  'BS.CapReserve',
  'BS.CashBank',
  'BS.CurrLiab',
  'BS.DefTaxLiab',
  'BS.FixedAssetsNet',
  'BS.Inventories',
  'BS.LTInvest',
  'BS.LoansAdvGiven',
  'BS.MiscExp',
  'BS.NetCurrAssets',
  'BS.NoAccCashBal',
  'BS.NoAccCreditors',
  'BS.NoAccDebtors',
  'BS.NoAccStock',
  'BS.OthCurrAssets',
  'BS.OthReserve',
  'BS.PropCapital',
  'BS.Provisions',
  'BS.RevSurplus',
  'BS.STInvest',
  'BS.SecuredLoansFin',
  'BS.SecuredLoansOth',
  'BS.SourcesTotal',
  'BS.StatReserve',
  'BS.SundryDebtors',
  'BS.TotAdvances',
  'BS.TotCurrAssets',
  'BS.TotCurrLiab',
  'BS.TotInvest',
  'BS.TotLoanFunds',
  'BS.TotPropFund',
  'BS.TotReserve',
  'BS.UnsecuredLoans',
  'BTI.TI_10AA',
  'BTI.TI_AggIncome',
  'BTI.TI_BFLA',
  'BTI.TI_CFLosses',
  'BTI.TI_CG',
  'BTI.TI_CYLA',
  'BTI.TI_DeemedAMT',
  'BTI.TI_GTI',
  'BTI.TI_HP',
  'BTI.TI_LTCG',
  'BTI.TI_NetAgri',
  'BTI.TI_OS',
  'BTI.TI_PGBP',
  'BTI.TI_STCG',
  'BTI.TI_Salary',
  'BTI.TI_SpecialInGTI',
  'BTI.TI_SpecialIncome',
  'BTI.TI_Total6',
  'BTI.TI_TotalIncome',
  'BTI.TI_VIA_a',
  'BTI.TI_VIA_b',
  'BTTI.TTI_234A',
  'BTTI.TTI_234B',
  'BTTI.TTI_234C',
  'BTTI.TTI_234F',
  'BTTI.TTI_234I',
  'BTTI.TTI_AMTCredit',
  'BTTI.TTI_AggLiab',
  'BTTI.TTI_AgriRebate',
  'BTTI.TTI_Cess',
  'BTTI.TTI_GrossLiab',
  'BTTI.TTI_GrossTax',
  'BTTI.TTI_NetLiab',
  'BTTI.TTI_Payable',
  'BTTI.TTI_Rebate87A',
  'BTTI.TTI_Refund',
  'BTTI.TTI_Relief89',
  'BTTI.TTI_Relief90',
  'BTTI.TTI_Relief91',
  'BTTI.TTI_Surcharge',
  'BTTI.TTI_TaxAMT',
  'BTTI.TTI_TaxNormal',
  'BTTI.TTI_TaxPayable1d',
  'BTTI.TTI_TaxSpecial',
  'BTTI.TTI_TotalPaid',
  'CFL.BPLoss',
  'CFL.HPLoss',
  'CFL.LTCL',
  'CFL.RaceLoss',
  'CFL.STCL',
  'CFL.SpecLoss',
  'CFL.SpecifiedLoss',
  'CG.Balance',
  'CG.C1_TotalCG',
  'CG.C2_VDA_CG',
  'CG.C3_Total',
  'CG.CostNoIndex',
  'CG.D_54',
  'CG.D_54EC',
  'CG.D_54F',
  'CG.Expense',
  'CG.FMV31Jan18',
  'CG.F_Q1',
  'CG.F_Q2',
  'CG.F_Q3',
  'CG.F_Q4',
  'CG.F_Q5',
  'CG.LTCG_B10_PTI',
  'CG.LTCG_B11_DTAA',
  'CG.LTCG_B12_Total',
  'CG.LTCG_B1_IndexCost',
  'CG.LTCG_B1_LandBld',
  'CG.LTCG_B1e',
  'CG.LTCG_B2_SlumpSale',
  'CG.LTCG_B3_Bonds',
  'CG.LTCG_B4_112A',
  'CG.LTCG_B4_Exemption',
  'CG.LTCG_B5_ShareDeb',
  'CG.LTCG_B6_Other',
  'CG.LTCG_B7_115AD',
  'CG.LTCG_B9_Other',
  'CG.Qty',
  'CG.STCG_A1_Cost',
  'CG.STCG_A1_Exp',
  'CG.STCG_A1_Improve',
  'CG.STCG_A1_LandBld',
  'CG.STCG_A1e',
  'CG.STCG_A2',
  'CG.STCG_A3_111A',
  'CG.STCG_A5_NR',
  'CG.STCG_A6_Other',
  'CG.STCG_A7_PTI',
  'CG.STCG_A8_DTAA',
  'CG.STCG_A9_Total',
  'CG.SalePrice',
  'CG.SaleValue',
  'CYLA.BFLA_BFLoss',
  'CYLA.BFLA_Total',
  'CYLA.BFLA_UnabsDep',
  'CYLA.CYLA_BPLoss',
  'CYLA.CYLA_HPLoss',
  'CYLA.CYLA_OSLoss',
  'CYLA.CYLA_TotalSetoff',
  'D80C.Amount',
  'D80D.ParentCheckup',
  'D80D.ParentMedExp',
  'D80D.ParentPremium',
  'D80D.SelfCheckup',
  'D80D.SelfMedExp',
  'D80D.SelfPremium',
  'D80D.Total80D',
  'D80E.EEA_Interest',
  'D80E.EEB_Interest',
  'D80E.EE_Interest',
  'D80E.E_Interest',
  'D80G.Cash',
  'D80G.Eligible',
  'D80G.Other',
  'D80G.Total',
  'D80GGA.Cash',
  'D80GGA.Eligible',
  'D80GGA.Other',
  'D80GGA.Total',
  'D80GGC.Cash',
  'D80GGC.Eligible',
  'D80GGC.Other',
  'D80GGC.Total',
  'DEP.AddlDep',
  'DEP.Bld10_Dep',
  'DEP.Bld40_Dep',
  'DEP.Bld5_Dep',
  'DEP.DCG_Total',
  'DEP.DEP_Total',
  'DEP.Furn10_Dep',
  'DEP.Intang25_Dep',
  'DEP.PM15_Add',
  'DEP.PM15_Dep',
  'DEP.PM15_Sale',
  'DEP.PM15_WDV',
  'DEP.PM30_Dep',
  'DEP.PM40_Dep',
  'DEP.PM45_Dep',
  'DEP.Ships20_Dep',
  'EI.EI_AgriExp',
  'EI.EI_AgriGross',
  'EI.EI_AgriLossBF',
  'EI.EI_AgriNet',
  'EI.EI_AgriRule',
  'EI.EI_DTAA',
  'EI.EI_FirmShare',
  'EI.EI_Interest',
  'EI.EI_Other',
  'EI.EI_PTI',
  'EI.EI_Total',
  'ESOP.ESOP_TaxCF',
  'ESOP.ESOP_TaxDeferredBF',
  'ESOP.ESOP_TaxPayableCY',
  'ESR.ESR_35CCC',
  'ESR.ESR_35CCD',
  'ESR.ESR_35_1_i',
  'ESR.ESR_35_1_ii',
  'ESR.ESR_35_1_iia',
  'ESR.ESR_35_1_iii',
  'ESR.ESR_35_1_iv',
  'ESR.ESR_35_2AA',
  'ESR.ESR_35_2AB',
  'ESR.ESR_Excess',
  'FA.CloseBal',
  'FA.IncomeAccrued',
  'FA.PeakBal',
  'FSI.IncomeFrgn',
  'FSI.ReliefE',
  'FSI.TaxPaidFrgn',
  'FSI.TaxPayableIN',
  'GEN.AcqCost',
  'GEN.AcqShares',
  'GEN.ClosingCost',
  'GEN.ClosingShares',
  'GEN.IssuePrice',
  'GEN.OpeningCost',
  'GEN.OpeningShares',
  'GEN.PinCode',
  'GEN.SaleConsid',
  'GEN.StayInIndiaDays',
  'GEN.TransferShares',
  'GSTS.Turnover',
  'HP.AnnualValue',
  'HP.ArrearsRent',
  'HP.GrossRent',
  'HP.IncomeHP',
  'HP.Interest24b',
  'HP.MunTax',
  'HP.OwnShare',
  'HP.StdDed30',
  'HP.TotalHP',
  'HP.UnrealRent',
  'ICDS.ICDS_I',
  'ICDS.ICDS_II',
  'ICDS.ICDS_III',
  'ICDS.ICDS_IV',
  'ICDS.ICDS_IX',
  'ICDS.ICDS_V',
  'ICDS.ICDS_VI',
  'ICDS.ICDS_VII',
  'ICDS.ICDS_VIII',
  'ICDS.ICDS_X',
  'ICDS.ICDS_XI',
  'IT.TaxAmt',
  'MFG.ClosingStock',
  'MFG.CostGoodsProduced',
  'MFG.DirectExpTotal',
  'MFG.DirectWages',
  'MFG.FactoryDep',
  'MFG.FactoryOverheads',
  'MFG.OpRawMat',
  'MFG.OpTotal',
  'MFG.OpWIP',
  'MFG.Purchases',
  'MFG.TotalDebits',
  'OI.Allow40PY',
  'OI.Allow43B',
  'OI.Deemed33AB',
  'OI.Disallow14A',
  'OI.Disallow36',
  'OI.Disallow37',
  'OI.Disallow40',
  'OI.Disallow40A',
  'OI.Disallow43B',
  'OI.ICDSDecrease',
  'OI.ICDSIncrease',
  'OI.IntMSME23',
  'OI.MSMEBeyond',
  'OI.NotCredited5f',
  'OI.OutstandingTax12i',
  'OI.Profit41',
  'OS.AccumPF2c',
  'OS.AnySpecial2d',
  'OS.DTAA2f',
  'OS.Ded57Exp',
  'OS.Ded57Int',
  'OS.Ded57iia',
  'OS.Dep3b',
  'OS.DivQ1',
  'OS.DivQ2',
  'OS.DivQ3',
  'OS.DivQ4',
  'OS.DivQ5',
  'OS.Dividend1a',
  'OS.FamilyPension',
  'OS.Gross1',
  'OS.Income56_2x',
  'OS.Income89A_OS',
  'OS.IntDeposits',
  'OS.IntITRefund',
  'OS.IntSavings',
  'OS.Interest1b',
  'OS.Lottery2ai',
  'OS.Net6',
  'OS.OnlineGames2aii',
  'OS.PTISpecial2e',
  'OS.RaceHorses8e',
  'OS.Relief89A_5a',
  'OS.Rental1c',
  'OS.Total7',
  'OS.Total9',
  'OS.Unexplained2b',
  'PL.Amt',
  'PL.AmtAvailAppr',
  'PL.Appropriations',
  'PL.BadDebt',
  'PL.BalBroughtFwd',
  'PL.BalCarriedBS',
  'PL.CommissionTot',
  'PL.Depreciation52',
  'PL.DividendInc14iii',
  'PL.EmpComp',
  'PL.GR44ADA',
  'PL.GT44ADBank',
  'PL.GT44ADCash',
  'PL.GT44ADOther',
  'PL.GrossProfitTrf',
  'PL.Insurance',
  'PL.InterestTot',
  'PL.Months',
  'PL.NA_BusExp',
  'PL.NA_BusGP',
  'PL.NA_BusGR',
  'PL.NA_BusNP',
  'PL.NA_ProfExp',
  'PL.NA_ProfGP',
  'PL.NA_ProfGR',
  'PL.NA_ProfNP',
  'PL.NA_Total',
  'PL.NPBT',
  'PL.OpeningStockPL',
  'PL.OthPresGR',
  'PL.OthPresNP',
  'PL.OtherExp',
  'PL.OtherIncTotal',
  'PL.OtherProv',
  'PL.PAT',
  'PL.PBIDT',
  'PL.PI44ADA',
  'PL.PI44ADBank',
  'PL.PI44ADCash',
  'PL.PI44AE',
  'PL.PresInc',
  'PL.ProfFees',
  'PL.ProvBadDebt',
  'PL.ProvCurrTax',
  'PL.ProvDefTax',
  'PL.RoyaltyTot',
  'PL.SpecExp',
  'PL.SpecGP',
  'PL.SpecNet',
  'PL.SpecTurnover',
  'PL.Tonnage',
  'PL.TotalCredits',
  'PTI.Amount',
  'PTI.TDSAmt',
  'RA.Cash',
  'RA.Eligible',
  'RA.Other',
  'RA.Total',
  'S.EntAllow',
  'S.ExemptAllow',
  'S.GrossSalary',
  'S.HRABasicDA',
  'S.HRAExempt',
  'S.HRAReceived',
  'S.HRARentPaid',
  'S.Income89A_1d',
  'S.Income89A_1e',
  'S.IncomeSalaries',
  'S.NetSalary',
  'S.Perq17_2',
  'S.ProfTax',
  'S.Profit17_3',
  'S.Relief89A',
  'S.Sal17_1',
  'S.StdDeduction',
  'S10AA.Amt10AA',
  'S5A.BP5A',
  'S5A.CG5A',
  'S5A.HP5A',
  'S5A.OS5A',
  'S5A.Tot5A',
  'SPI.Capital',
  'SPI.InterestRecd',
  'SPI.PctShare',
  'SPI.RemunRecd',
  'SPI.SI_111A',
  'SPI.SI_112A',
  'SPI.SI_115BB',
  'SPI.SI_115BBE',
  'SPI.SI_115BBH',
  'SPI.SI_115BBJ',
  'SPI.SI_Total',
  'SPI.ShareAmt',
  'TCS.TCSCF',
  'TCS.TCSClaimed',
  'TCS.TCSCollected',
  'TDS1.IncomeSal',
  'TDS1.TaxDeducted',
  'TDS2.GrossAmt',
  'TDS2.TDSCF',
  'TDS2.TDSClaimed',
  'TDS2.TDSDeducted',
  'TDS3.GrossRentAmt',
  'TDS3.TDSClm3',
  'TDS3.TDSDed3',
  'TPSA.TPSA_Cess',
  'TPSA.TPSA_Net',
  'TPSA.TPSA_Paid',
  'TPSA.TPSA_Primary',
  'TPSA.TPSA_Surch',
  'TPSA.TPSA_Tax18',
  'TPSA.TPSA_TotalTax',
  'TRD.ClosingStockTrd',
  'TRD.CostGoodsFromMfg',
  'TRD.DirectExpTrd',
  'TRD.DutiesTaxesPaid',
  'TRD.DutiesTotal',
  'TRD.FOIncome',
  'TRD.FOTurnover',
  'TRD.GrossProfit',
  'TRD.GrossReceipts',
  'TRD.GrossReceiptsGST',
  'TRD.IntradayIncome',
  'TRD.IntradayTurnover',
  'TRD.OpStockFG',
  'TRD.OtherOpRevenue',
  'TRD.PurchasesTrd',
  'TRD.SaleGoods',
  'TRD.SaleServices',
  'TRD.TotRevenueOps',
  'TRD.TotalOfCredits',
  'UD.Adj115BAC',
  'UD.Allow35_4',
  'UD.DepBF',
  'UD.DepCF',
  'UD.SetOff',
  'VDA.Consideration',
  'VDA.CostAcq',
  'VDA.Income',
  'VIA.VIA_80C',
  'VIA.VIA_80CCC',
  'VIA.VIA_80CCD1',
  'VIA.VIA_80CCD1B',
  'VIA.VIA_80CCD2',
  'VIA.VIA_80CCH',
  'VIA.VIA_80D',
  'VIA.VIA_80DD',
  'VIA.VIA_80DDB',
  'VIA.VIA_80E',
  'VIA.VIA_80EE',
  'VIA.VIA_80EEA',
  'VIA.VIA_80EEB',
  'VIA.VIA_80G',
  'VIA.VIA_80GG',
  'VIA.VIA_80GGA',
  'VIA.VIA_80GGC',
  'VIA.VIA_80IA',
  'VIA.VIA_80IB',
  'VIA.VIA_80IE',
  'VIA.VIA_80JJAA',
  'VIA.VIA_80QQB',
  'VIA.VIA_80RRB',
  'VIA.VIA_80TTA',
  'VIA.VIA_80TTB',
  'VIA.VIA_80U',
  'VIA.VIA_PartB',
  'VIA.VIA_PartC',
  'VIA.VIA_Total',
]);

/** Fields the department stores in upper case. */
export const SCH_UPPER: ReadonlySet<string> = new Set([
  'D80DD.DD_DependentPAN',
  'D80G.DoneePAN',
  'D80GGA.DoneePAN',
  'D80GGC.PartyPAN',
  'GEN.AuditFirmPAN',
  'GEN.CoPAN',
  'GEN.CompanyPAN',
  'GEN.PAN',
  'GEN.RepPAN',
  'GEN.SpousePAN',
  'PTI.FundPAN',
  'RA.PAN',
  'S.EmployerTAN',
  'S5A.SpousePAN5A',
  'SPI.FirmPAN',
  'TDS3.TenantPAN',
  'VER.VerPAN',
  'BTTI.BankName',
  'CG.ShareName',
  'D80G.DoneeName',
  'D80GGA.DoneeName',
  'D80GGC.PartyName',
  'GEN.City',
  'GEN.CoName',
  'GEN.CompanyName',
  'GEN.FirstName',
  'GEN.FlatDoorNo',
  'GEN.Locality',
  'GEN.MiddleName',
  'GEN.PremiseName',
  'GEN.RoadStreet',
  'GEN.SurNameOrOrgName',
  'HP.TenantName',
  'NOB.Description',
  'NOB.TradeName',
  'PL.DebtorName',
  'PTI.FundName',
  'RA.Name',
  'S.EmployerName',
  'SPI.FirmName',
  'TCS.CollectorName',
  'TDS1.EmpName',
  'TDS2.DeductorName',
  'TDS3.TenantName',
  'VER.VerFatherName',
  'VER.VerName',
  'VER.VerPlace',
]);

/** State name to the departmental state code. */
export const SCH_STATE: Readonly<Record<string, string>> = {
  'ANDAMAN AND NICOBAR ISLANDS': '01',
  'ANDHRA PRADESH': '02',
  'ARUNACHAL PRADESH': '03',
  ASSAM: '04',
  BIHAR: '05',
  CHANDIGARH: '06',
  'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU': '07',
  DELHI: '09',
  GOA: '10',
  GUJARAT: '11',
  HARYANA: '12',
  'HIMACHAL PRADESH': '13',
  'JAMMU AND KASHMIR': '14',
  KARNATAKA: '15',
  KERALA: '16',
  LAKSHADWEEP: '17',
  'MADHYA PRADESH': '18',
  MAHARASHTRA: '19',
  MANIPUR: '20',
  MEGHALAYA: '21',
  MIZORAM: '22',
  NAGALAND: '23',
  ODISHA: '24',
  PUDUCHERRY: '25',
  PUNJAB: '26',
  RAJASTHAN: '27',
  SIKKIM: '28',
  'TAMIL NADU': '29',
  TRIPURA: '30',
  'UTTAR PRADESH': '31',
  'WEST BENGAL': '32',
  CHHATTISGARH: '33',
  UTTARAKHAND: '34',
  JHARKHAND: '35',
  TELANGANA: '36',
  LADAKH: '37',
};

/**
 * Country name to the departmental country code. This is the prototype's list
 * and it stops at RUSSIAN FEDERATION; the published list runs further.
 */
export const SCH_COUNTRY: Readonly<Record<string, string>> = {
  AFGHANISTAN: '93',
  'ALAND ISLANDS': '1001',
  ALBANIA: '355',
  ALGERIA: '213',
  'AMERICAN SAMOA': '684',
  ANDORRA: '376',
  ANGOLA: '244',
  ANGUILLA: '1264',
  ANTARCTICA: '1010',
  'ANTIGUA AND BARBUDA': '1268',
  ARGENTINA: '54',
  ARMENIA: '374',
  ARUBA: '297',
  AUSTRALIA: '61',
  AUSTRIA: '43',
  AZERBAIJAN: '994',
  BAHAMAS: '1242',
  BAHRAIN: '973',
  BANGLADESH: '880',
  BARBADOS: '1246',
  BELARUS: '375',
  BELGIUM: '32',
  BELIZE: '501',
  BENIN: '229',
  BERMUDA: '1441',
  BHUTAN: '975',
  'BOLIVIA (PLURINATIONAL STATE OF)': '591',
  'BONAIRE, SINT EUSTATIUS AND SABA': '1002',
  'BOSNIA AND HERZEGOVINA': '387',
  BOTSWANA: '267',
  'BOUVET ISLAND': '1003',
  BRAZIL: '55',
  'BRITISH INDIAN OCEAN TERRITORY': '1014',
  'BRUNEI DARUSSALAM': '673',
  BULGARIA: '359',
  'BURKINA FASO': '226',
  BURUNDI: '257',
  'CABO VERDE': '238',
  CAMBODIA: '855',
  CAMEROON: '237',
  CANADA: '1',
  'CAYMAN ISLANDS': '1345',
  'CENTRAL AFRICAN REPUBLIC': '236',
  CHAD: '235',
  CHILE: '56',
  CHINA: '86',
  'CHRISTMAS ISLAND': '9',
  'COCOS (KEELING) ISLANDS': '672',
  COLOMBIA: '57',
  COMOROS: '270',
  CONGO: '242',
  'CONGO (DEMOCRATIC REPUBLIC OF THE)': '243',
  'COOK ISLANDS': '682',
  'COSTA RICA': '506',
  'COTE DIVOIRE': '225',
  CROATIA: '385',
  CUBA: '53',
  CURACAO: '1015',
  CYPRUS: '357',
  CZECHIA: '420',
  DENMARK: '45',
  DJIBOUTI: '253',
  DOMINICA: '1767',
  'DOMINICAN REPUBLIC': '1809',
  ECUADOR: '593',
  EGYPT: '20',
  'EQUATORIAL GUINEA': '240',
  ERITREA: '291',
  ETHIOPIA: '251',
  'FALKLAND ISLANDS (MALVINAS)': '500',
  'FAROE ISLANDS': '298',
  FIJI: '679',
  FINLAND: '358',
  FRANCE: '33',
  'FRENCH GUIANA': '594',
  'FRENCH POLYNESIA': '689',
  'FRENCH SOUTHERN TERRITORIES': '1004',
  GABON: '241',
  GAMBIA: '220',
  GEORGIA: '995',
  GHANA: '233',
  GIBRALTAR: '350',
  GREECE: '30',
  GREENLAND: '299',
  GUADELOUPE: '590',
  GUAM: '1671',
  GUATEMALA: '502',
  GUERNSEY: '1481',
  GUINEA: '224',
  'GUINEA-BISSAU': '245',
  'HOLY SEE': '6',
  HONDURAS: '504',
  'HONG KONG': '852',
  ICELAND: '354',
  INDIA: '91',
  'IRAN (ISLAMIC REPUBLIC OF)': '98',
  IRAQ: '964',
  ISRAEL: '972',
  ITALY: '5',
  JERSEY: '1534',
  JORDAN: '962',
  KAZAKHSTAN: '7',
  KENYA: '254',
  KIRIBATI: '686',
  'KOREA (DEMOCRATIC PEOPLES REPUBLIC OF)': '850',
  'KOREA (REPUBLIC OF)': '82',
  KUWAIT: '965',
  KYRGYZSTAN: '996',
  'LAO PEOPLES DEMOCRATIC REPUBLIC': '856',
  LATVIA: '371',
  LEBANON: '961',
  LESOTHO: '266',
  LIBERIA: '231',
  LIBYA: '218',
  LIECHTENSTEIN: '423',
  LITHUANIA: '370',
  LUXEMBOURG: '352',
  MACAO: '853',
  'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)': '389',
  MADAGASCAR: '261',
  MALAWI: '265',
  MALAYSIA: '60',
  MALDIVES: '960',
  MALI: '223',
  MALTA: '356',
  'MARSHALL ISLANDS': '692',
  MARTINIQUE: '596',
  MAURITANIA: '222',
  MAURITIUS: '230',
  MAYOTTE: '269',
  MEXICO: '52',
  'MICRONESIA (FEDERATED STATES OF)': '691',
  'MOLDOVA (REPUBLIC OF)': '373',
  MONACO: '377',
  MONGOLIA: '976',
  MONTENEGRO: '382',
  MONTSERRAT: '1664',
  MOROCCO: '212',
  MOZAMBIQUE: '258',
  MYANMAR: '95',
  NAMIBIA: '264',
  NAURU: '674',
  NEPAL: '977',
  NETHERLANDS: '31',
  'NEW CALEDONIA': '687',
  'NEW ZEALAND': '64',
  NICARAGUA: '505',
  NIGER: '227',
  NIGERIA: '234',
  NIUE: '683',
  'NORFOLK ISLAND': '15',
  'NORTHERN MARIANA ISLANDS': '1670',
  OMAN: '968',
  PAKISTAN: '92',
  PALAU: '680',
  PARAGUAY: '595',
  PERU: '51',
  PHILIPPINES: '63',
  PITCAIRN: '1011',
  POLAND: '48',
  PORTUGAL: '14',
  'PUERTO RICO': '1787',
  QATAR: '974',
  REUNION: '262',
  ROMANIA: '40',
  'RUSSIAN FEDERATION': '8',
};

/** Fields whose value is resolved through SCH_STATE. */
export const SCH_STATE_FIELDS: ReadonlySet<string> = new Set([
  'GEN.State',
]);

/** Fields whose value is resolved through SCH_COUNTRY. */
export const SCH_COUNTRY_FIELDS: ReadonlySet<string> = new Set([
  'GEN.Country',
]);
